### ISSUE TITLE
KeyError: 'bytesize'

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#150]
```
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets$ flock -E 0 -e -n /home/dandi/.run/backup2datalad-cron.lock python -m tools.backups2datalad -l WARNING -J 5 --target /mnt/backup/dandi/dandisets update-from-backup --zarr-target /mnt/backup/dandi/dandizarrs --backup-remote dandi-dandisets-dropbox --zarr-backup-remote dandi-dandizarrs-dropbox --gh-org dandisets --zarr-gh-org dandizarrs -e '000108$'
A newer version (0.39.5) of dandi/dandi-cli is available. You are using 0.36.0
Push to 'github':  25%|█████████████████████████████▌                                                                                        | 1.00/4.00 [00:00<00:00, 5.13k Steps/s]Update availability for 'github':  75%|████████████████████████████████████████████████████████████████████████████▌                         | 3.00/4.00 [00:00<00:00, 16.1k Steps/s]2022-05-09T15:41:09-0400 [WARNING ] backups2datalad Retrying HEAD request to https://api.dandiarchive.org/api/zarr/7723d02f-1f71-4553-a7b0-47bda1ae8b42.zarr/0/0/0/7/6/14 in 1.250000 seconds as it raised ReadTimeout:
[INFO   ] Remote origin not usable by git-annex; setting annex-ignore
[INFO   ] https://github.com/dandizarrs/7723d02f-1f71-4553-a7b0-47bda1ae8b42/config download failed: Not Found
[INFO   ] access to 1 dataset sibling dandi-dandizarrs-dropbox not auto-enabled, enable with:
|               datalad siblings -d "/mnt/backup/dandi/dandisets/000243/sub-S01/anat/sub-S01_T2w.ngff" enable -s dandi-dandizarrs-dropbox
                                                                                                                                                                                     Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 311, in <module>
    main()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 159, in update_from_backup
    datasetter.update_from_backup(dandisets, exclude=exclude)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 84, in update_from_backup
    stats = self.get_dandiset_stats(ds)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 219, in get_dandiset_stats
    size += filestat["bytesize"]
KeyError: 'bytesize'

```

I will retry the job now (after cleaning if needed) but I have disabled cron job for now

**Comment by jwodder** [comment]
@yarikoptic `filestat` is a `dict` yielded by `Dataset.status()`.  I'm guessing that the `dict` in question represents a Zarr sub-dataset; what do the fields of such a `dict` look like, and how can a sub-dataset's size be determined?

**Comment by yarikoptic** [comment]
subdatataset's record doesn't have bytesize:
```
$> datalad -f json_pp status --annex all -d . ds000003
{
  "action": "status",
  "gitshasum": "c09053726f9f9cac58b2a1db43a4b6f57d67ccc3",
  "parentds": "/home/yoh/datalad/openneuro",
  "path": "/home/yoh/datalad/openneuro/ds000003",
  "prev_gitshasum": "c09053726f9f9cac58b2a1db43a4b6f57d67ccc3",
  "refds": "/home/yoh/datalad/openneuro",
  "state": "clean",
  "status": "ok",
  "type": "dataset"
}
```
so I guess just call `get_dandiset_stats` on that subdataset recursively 
call it with `annex='all'` and then add up only for records which have `action=="status"` and which have `bytesize` since might be `type="directory"` which would have none.
