### ISSUE TITLE
retry for longer while talking to our server

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#162]
it seems we retry only until delay of 10 seconds or so.  Let's increase the stepping to grow in larger incremens faster and a few more times so it spreads into a few minutes :
```
2022-05-26T10:43:57-0400 [WARNING ] backups2datalad Retrying GET request to https://api.dandiarchive.org/api/assets/45c9484b-4c41-446a-9855-d939d8153e0d/ in 4.768372 seconds as it raised ConnectTimeout:
2022-05-26T10:44:18-0400 [WARNING ] backups2datalad Retrying GET request to https://api.dandiarchive.org/api/assets/45c9484b-4c41-446a-9855-d939d8153e0d/ in 5.960464 seconds as it raised ConnectTimeout:
2022-05-26T10:44:55-0400 [WARNING ] backups2datalad Retrying GET request to https://api.dandiarchive.org/api/assets/45c9484b-4c41-446a-9855-d939d8153e0d/ in 7.450581 seconds as it raised ConnectTimeout:
2022-05-26T10:45:35-0400 [WARNING ] backups2datalad Retrying GET request to https://api.dandiarchive.org/api/assets/45c9484b-4c41-446a-9855-d939d8153e0d/ in 9.313226 seconds as it raised ConnectTimeout:
2022-05-26T10:46:55-0400 [ERROR   ] backups2datalad Operation failed with exception:
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpcore/backends/asyncio.py", line 101, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_core/_sockets.py", line 218, in connect_tcp
    await event.wait()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 658, in __aexit__
    raise CancelledError
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpcore/backends/asyncio.py", line 101, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError

....
    raise e
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/util.py", line 419, in arequest
    r = await client.request(method, url, follow_redirects=True)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_client.py", line 1506, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_client.py", line 1593, in send
    response = await self._send_handling_auth(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_client.py", line 1621, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_client.py", line 1658, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_client.py", line 1695, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout
```

**Comment by jwodder** [comment]
@yarikoptic Currently, when sleeping between retries, the *n*-th wait (starting at `n=0`) lasts for `(1.25 ** n) * 1.25` seconds.  What do you want those values changed to?

**Comment by yarikoptic** [comment]
greedy me: let's do
```
In [7]: [(1.8**n) for n in range(10)]
Out[7]: 
[1.0,
 1.8,
 3.24,
 5.832000000000001,
 10.4976,
 18.895680000000002,
 34.012224,
 61.22200320000001,
 110.19960576000003,
 198.35929036800005]

``` 

so totaling to up to ~7 minutes.  hopefully that would be enough for anything to come back to its senses
