### ISSUE TITLE
Ensure that github sibling is created

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#166]
Due to various other issues we can end up in a "crashed" state without github sibling being configured.  

<details>
<summary>Here is a traceback from crash while trying to backup 108 </summary> 

```shell
publish(error): . [Unknown push target 'github'. Known targets: 'dandi-dandizarrs-dropbox'.]
action summary:
  publish (error: 1)
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 327, in <module>
    main()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 161, in update_from_backup
    datasetter.update_from_backup(dandisets, exclude=exclude)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 77, in update_from_backup
    changed = self.sync_dataset(d, ds)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 144, in sync_dataset
    syncer.sync_assets()
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/syncer.py", line 36, in sync_assets
    self.report = anyio.run(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/asyncer.py", line 408, in async_assets
    nursery.start_soon(dm.read_addurl)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 660, in __aexit__
    raise ExceptionGroup(exceptions)
anyio._backends._asyncio.ExceptionGroup: 2 exceptions were raised in the task group:
----------------------------
Traceback (most recent call last):
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/zarr.py", line 426, in sync_zarr
    await anyio.to_thread.run_sync(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/zarr.py", line 492, in save_and_push
    ds.push(to="github", jobs=jobs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 502, in apply_func
    return f(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 447, in eval_func
    return return_func(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 439, in return_func
    results = list(results)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 424, in generator_func
    raise IncompleteResultsError(
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'publish',
  'message': "Unknown push target 'github'. Known targets: "
             "'dandi-dandizarrs-dropbox'.",
  'path': '/mnt/backup/dandi/dandizarrs/8b0493dd-32d6-4f75-8ca2-b57b28fc9695',
  'refds': '/mnt/backup/dandi/dandizarrs/8b0493dd-32d6-4f75-8ca2-b57b28fc9695',
  'status': 'error'}]
----------------------------
Traceback (most recent call last):
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/zarr.py", line 426, in sync_zarr
    await anyio.to_thread.run_sync(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/zarr.py", line 492, in save_and_push
    ds.push(to="github", jobs=jobs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 502, in apply_func
    return f(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 447, in eval_func
    return return_func(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 439, in return_func
    results = list(results)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 424, in generator_func
    raise IncompleteResultsError(
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'publish',
  'message': "Unknown push target 'github'. Known targets: "
             "'dandi-dandizarrs-dropbox'.",
  'path': '/mnt/backup/dandi/dandizarrs/0bda7c93-58b3-4b94-9a83-453e1c370c24',
  'refds': '/mnt/backup/dandi/dandizarrs/0bda7c93-58b3-4b94-9a83-453e1c370c24',
  'status': 'error'}]
----------------------------
Traceback (most recent call last):
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/zarr.py", line 426, in sync_zarr
    await anyio.to_thread.run_sync(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/zarr.py", line 492, in save_and_push
    ds.push(to="github", jobs=jobs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 502, in apply_func
    return f(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 447, in eval_func
    return return_func(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 439, in return_func
    results = list(results)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 424, in generator_func
    raise IncompleteResultsError(
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'publish',
  'message': "Unknown push target 'github'. Known targets: "
             "'dandi-dandizarrs-dropbox'.",
  'path': '/mnt/backup/dandi/dandizarrs/0bda7c93-58b3-4b94-9a83-453e1c370c24',
  'refds': '/mnt/backup/dandi/dandizarrs/0bda7c93-58b3-4b94-9a83-453e1c370c24',
  'status': 'error'}]
```

</details>

<details>
<summary>and majority of dandizarrs on drogon are missing the github sibling:</summary> 

```shell
(base) dandi@drogon:/mnt/backup/dandi/dandizarrs$ for ds in *-*; do git -C $ds remote | grep -q github || echo "$ds is missing github"; done
020f7130-3a59-4140-b01d-ac2180917b05 is missing github
04c1418b-bdca-4f4f-bcf7-2dc194bcc461 is missing github
090506c6-fe41-4994-a25d-d82497ea6322 is missing github
0bda7c93-58b3-4b94-9a83-453e1c370c24 is missing github
0caa4039-cfc8-4a12-aa9a-df859d06e9a4 is missing github
15662576-2df1-4035-a37e-b9f74fd5cb5b is missing github
15c2063b-3183-4fa9-b018-9865b47c2a7f is missing github
16278cb5-d260-42ed-871d-692aea3aaec4 is missing github
175ac174-d3d1-446a-91a9-32994c1e04e9 is missing github
1825d3a0-81f4-4fe3-923b-a6149d059601 is missing github
214eb82c-4826-4e54-bd38-b7cfb9d6091e is missing github
21e4e2e9-9474-4568-8dee-ae9154316ddd is missing github
22550646-2a87-4a5c-9350-5ca248e4d48b is missing github
2df0d8c7-434e-4ae2-b92f-c94745e96867 is missing github
3542a2f4-fc77-4d97-888e-d04c8e46cf81 is missing github
3cba00fe-3f4c-49ba-afd1-cc80245316be is missing github
3d313fc2-0204-496d-bfa1-5c90951ee640 is missing github
484309b9-b4af-4d50-a752-5b98e63d77bd is missing github
4d85c62d-dbb3-445b-9016-4897fc0911a2 is missing github
4ea5a47f-10d6-48a7-8c1e-ce6ce511f9a7 is missing github
5e7bd723-0291-4e76-9efb-0fc37a30ff64 is missing github
5f92293e-0f63-4a8e-b4d4-19209d788867 is missing github
64596bfc-c702-4547-9453-6bee00a78f5a is missing github
68653f05-5fb5-4fdf-8f2b-09c07d40ae4e is missing github
7de41af3-8888-4148-b461-1f5d5e5f3965 is missing github
82a6d8ad-f5c0-4c83-a33a-28c141987461 is missing github
837ad88c-3397-4515-9a64-b247b5dafb11 is missing github
8b0493dd-32d6-4f75-8ca2-b57b28fc9695 is missing github
90467e9d-edaf-4d3c-906d-d86a78705f79 is missing github
96e5a768-e90c-4327-9d5a-1e2919acd8eb is missing github
a036e3f7-b491-4a1d-9fb0-657aed631d2d is missing github
a6069d30-946a-4870-9601-aed19c79d266 is missing github
a81b3341-8089-4c27-9a5f-0c2b79959495 is missing github
a9f3f454-8252-4d67-8c44-9a03288c241a is missing github
c4f25f08-db2a-438e-82e7-75614c7ea7ae is missing github
ccfebfc1-5331-48f6-b64d-730bdc8631f6 is missing github
ce741b71-4f63-4e90-be73-feba7cd3b912 is missing github
dac08897-699c-4114-b689-7e98beace7ea is missing github
f797ef06-5670-4494-a00b-3a6682e02399 is missing github
f7b37e71-99e3-4c4b-a61f-1fc19328e9a6 is missing github
ffc75449-ff75-4a33-84f9-3ac6eee72d8e is missing github
(base) dandi@drogon:/mnt/backup/dandi/dandizarrs$ for ds in *-*; do git -C $ds remote | grep -q github && echo "$ds has github"; done 
1efe6ed8-c5f2-4888-b1df-e372e24bb2b4 has github
21ba7569-326f-4c22-ba05-883bc2a4c9d0 has github
2cdcf251-b11b-4bf5-b13c-a54411030365 has github
338304db-6b4d-4626-b857-bf43db94298f has github
3579486b-378d-41d3-96c4-dc174417315d has github
5177a673-606b-46a8-9552-604d979ba396 has github
66dbcc6f-0396-441d-aea6-0af8d5500562 has github
711c0c20-f412-4cd9-8f84-d41b5dc15544 has github
7723d02f-1f71-4553-a7b0-47bda1ae8b42 has github
7ec13493-6606-4616-bcf1-8ac8e6850d0b has github
bf47be1a-4fed-4105-bcb4-c52534a45b82 has github
d241fe01-a13a-412c-9774-fc28518f41b9 has github
ef23e539-513e-49ad-8a0b-584bbaba8dfe has github
f7e3a560-c4a6-4652-b8c8-66afe580e4cb has github
```
</details>

for now I tried to fix up manually but part of the problem is that sibling was already created but just not configured:
```
(dandisets) dandi@drogon:/mnt/backup/dandi/dandizarrs$ for z in *-*; do git -C $z remote | grep -q github || echo "$z is missing github"; PYTHONPATH=$PWD/../dandisets/tools/ python -c "from backups2datalad.util import Dataset, create_github_sibling; print('$z', create_github_sibling(Dataset('$z'), 'dandizarrs', 'github', 'dandi-dandizarrs-dropbox'))"; done
020f7130-3a59-4140-b01d-ac2180917b05 is missing github
create_sibling_github(error): [A repository 'github' already exists at 'https://api.github.com', use existing=reconfigure to use it as a sibling]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/util.py", line 498, in create_github_sibling
    ds.create_sibling_github(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 502, in apply_func
    return f(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 447, in eval_func
    return return_func(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 439, in return_func
    results = list(results)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 424, in generator_func
    raise IncompleteResultsError(
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'create_sibling_github',
  'message': ("A repository '%s' already exists at '%s', use "
              'existing=reconfigure to use it as a sibling',
              'github',
              'https://api.github.com'),
  'preexisted': True,
  'refds': '/mnt/backup/dandi/dandizarrs/020f7130-3a59-4140-b01d-ac2180917b05',
  'status': 'error'}]
...
```

filed https://github.com/datalad/datalad/issues/6723 since (and good) we didn't just "skip" but "errorred", pushed e38d48c75b9962c2f0eba31049cdac1267264944 to interface `existing` and rerun with `existing="reconfigure"`

```
(dandisets) dandi@drogon:/mnt/backup/dandi/dandizarrs$ for z in *-*; do git -C $z remote | grep -q github || echo "$z is missing github"; PYTHONPATH=$PWD/../dandisets/tools/ python -c "from backups2datalad.util import Dataset, create_github_sibling; print('$z', create_github_sibling(Dataset('$z'), 'dandizarrs', 'github', 'dandi-dandizarrs-dropbox', existing='reconfigure'))"; done
020f7130-3a59-4140-b01d-ac2180917b05 is missing github
[INFO   ] Configure additional publication dependency on "dandi-dandizarrs-dropbox"
configure-sibling(ok): . (sibling)
action summary:
  configure-sibling (ok: 1)
  create_sibling_github (notneeded: 1)
020f7130-3a59-4140-b01d-ac2180917b05 True
04c1418b-bdca-4f4f-bcf7-2dc194bcc461 is missing github
[INFO   ] Configure additional publication dependency on "dandi-dandizarrs-dropbox"
configure-sibling(ok): . (sibling)
action summary:
  configure-sibling (ok: 1)
  create_sibling_github (notneeded: 1)
04c1418b-bdca-4f4f-bcf7-2dc194bcc461 True
090506c6-fe41-4994-a25d-d82497ea6322 is missing github
```

but overall, if we run into this situation again, I think it should be code which would do that -- if no `github` remote was found, call that create function to create one

**Comment by yarikoptic** [comment]
ehm, and I screwed up in above in that they all pointed to https://github.com/dandizarrs/github github repo! Fixing it all up now already wishing it was fixed up properly

**Comment by yarikoptic** [comment]
FTR the correct command to run was:
```
for z in *-*; do git -C $z remote | grep -q github || echo "$z is missing github"; PYTHONPATH=$PWD/../dandisets/tools/ python -c "from backups2datalad.util import Dataset, create_github_sibling; print('$z', create_github_sibling(Dataset('$z'), 'dandizarrs', '$z', 'dandi-dandizarrs-dropbox', existing='reconfigure'))"; done
```
