### ISSUE TITLE
Invoke `annex move` up to 5 times in case of error(s)

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#176]
got a run of `populate-zarrs` error out with 
```
move 6/0/0/0/0/5 (to dandi-dandizarrs-dropbox...) ok
move 6/0/0/0/0/2 (to dandi-dandizarrs-dropbox...) ok
(recording state in git...)
move: 2 failed
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 327, in <module>
    main()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 282, in populate_zarrs
    populate(p, backup_remote, f"Zarr {p.name}", datasetter.config.jobs)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 310, in populate
    subprocess.run(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git-annex', 'move', '-c', 'annex.retry=3', '--jobs', '5', '--to', 'dandi-dandizarrs-dropbox']' returned non-zero exit status 1.
```

IIRC @joeyh correctly, annex.retry doesn't even apply to all operations, so possibly it is just a matter of some connection fluke and no re-attempt was made.  Unfortunately I don't have a clue in which zarr it has happened due to excessive output (#172) to see if subsequent `move` would succeed but I would assume so.   I think in the case of a failed `move` we should retry.  Ideally we should keep retrying as number of errors goes down.  For that it is better to use `--json --json-error-messages` interface for the call of `move` (or datalad interface -- eg. `AnnexRepo.call_annex_records` or its internal counterpart to be able to enable progress bar or even `_call_annex_records_items_` if to keep it a generator if desired) and analyze the result.  If there were successes -- try one more time. If keeps erroring out -- time to give up.  Altogether e.g. up to 5 times.

**Comment by yarikoptic** [comment]
<details>
<summary>FWIW -- figured out what zarr that was and reran the script -- moved those 2 files just fine. confirms that re-invocation should help</summary> 

```shell
(dandisets) dandi@drogon:/mnt/backup/dandi/dandizarrs$ for f in */6/0/0/0/0/2; do d=${f%%/*}; echo -n "$d: "; git -C $d annex find --in here --not --in dandi-dandizarrs-dropbox | wc -l; done
04c1418b-bdca-4f4f-bcf7-2dc194bcc461: 0
0bda7c93-58b3-4b94-9a83-453e1c370c24: 0
15662576-2df1-4035-a37e-b9f74fd5cb5b: 0
15c2063b-3183-4fa9-b018-9865b47c2a7f: 0
1825d3a0-81f4-4fe3-923b-a6149d059601: 0
214eb82c-4826-4e54-bd38-b7cfb9d6091e: 0
21e4e2e9-9474-4568-8dee-ae9154316ddd: 0
3542a2f4-fc77-4d97-888e-d04c8e46cf81: 0
3cba00fe-3f4c-49ba-afd1-cc80245316be: 0
3d313fc2-0204-496d-bfa1-5c90951ee640: 0
484309b9-b4af-4d50-a752-5b98e63d77bd: 0
4ea5a47f-10d6-48a7-8c1e-ce6ce511f9a7: 0
5e7bd723-0291-4e76-9efb-0fc37a30ff64: 2
68653f05-5fb5-4fdf-8f2b-09c07d40ae4e: 0
837ad88c-3397-4515-9a64-b247b5dafb11: 0
8b0493dd-32d6-4f75-8ca2-b57b28fc9695: 0
96e5a768-e90c-4327-9d5a-1e2919acd8eb: 0
c4f25f08-db2a-438e-82e7-75614c7ea7ae: 0
dac08897-699c-4114-b689-7e98beace7ea: 0
ffc75449-ff75-4a33-84f9-3ac6eee72d8e: 0
(dandisets) dandi@drogon:/mnt/backup/dandi/dandizarrs$ cd ../dandisets/

(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets$ python -m tools.backups2datalad    -l DEBUG    -J 5    populate-zarrs --zarr-target "$zarrds" dandi-dandizarrs-dropbox  5e7bd723-0291-4e76-9efb-0fc37a30ff64
2022-06-02T13:05:24-0400 [INFO    ] backups2datalad Saving logs to .git/dandi/backups2datalad/2022.06.02.17.05.24Z.log
2022-06-02T13:05:24-0400 [INFO    ] backups2datalad Downloading files for Zarr 5e7bd723-0291-4e76-9efb-0fc37a30ff64
2022-06-02T13:05:50-0400 [INFO    ] backups2datalad Moving files for Zarr 5e7bd723-0291-4e76-9efb-0fc37a30ff64 to backup remote
move 1/0/0/1/3/46 (to dandi-dandizarrs-dropbox...) ok
move 1/0/0/1/3/26 (to dandi-dandizarrs-dropbox...) ok
(recording state in git...)

```
</details>

**Comment by joeyh** [comment]
annex.retry applies to all operations that transfer content. It
does not currently apply to other operations, such as dropping content.
So if the move transferred the content successfully but then failed to drop,
it would not retry it.

I think it would be worth considering making annex.retry also apply to
drops. Not to other operations that might fail though. But there are
considerations, including the common case where a drop fails because
there are not enough copies. Retrying such a failed drop is probably
pointless and annoying. So it would probably need to only apply to drops
where there was a failure to communicate with a remote.

-- 
see shy jo
