### ISSUE TITLE
populate-zarrs: assert self.p.stdin is not None

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#188]
never saw that one before
```
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets$ PATH=/home/dandi/git-annexes/10.20220526-gd04146e0c-debuglocks:$PATH python -m tools.backups2datalad    -l DEBUG    -J 5    populate-zarrs --zarr-target "$zarrds" dandi-dandizarrs-dropbox  
A newer version (0.40.1) of dandi/dandi-cli is available. You are using 0.40.0
2022-06-07T09:09:35-0400 [INFO    ] backups2datalad Saving logs to .git/dandi/backups2datalad/2022.06.07.13.09.35Z.log
2022-06-07T09:09:36-0400 [DEBUG   ] asyncio Using selector: EpollSelector
2022-06-07T09:09:36-0400 [INFO    ] backups2datalad Downloading files for Zarr 15662576-2df1-4035-a37e-b9f74fd5cb5b
2022-06-07T09:09:36-0400 [DEBUG   ] backups2datalad Running git-annex -c annex.retry=3 --jobs 5 --from=web --not --in dandi-dandizarrs-dropbox --and --not --in here
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 377, in <module>
    main()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 302, in populate_zarrs
    anyio.run(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 315, in populate
    await call_annex_json(
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 365, in call_annex_json
    failed += 1
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/abc/_resources.py", line 25, in __aexit__
    await self.aclose()
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/util.py", line 142, in aclose
    assert self.p.stdin is not None
AssertionError
```

**Comment by jwodder** [comment]
@yarikoptic This is a consequence of #184.
