### ISSUE TITLE
git gc exits with 128

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#191]
I encountered it before but didn't report.. it seems to persist:

```
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets$ PATH=/home/dandi/git-annexes/10.20220525+git57-ge796080f3-1~ndall+1/usr/lib/git-annex.linux:$PATH  python -m tools.backups2datalad -l WARNING -J 5 --target /mnt/backup/dandi/dandisets update-from-backup --zarr-target /mnt/backup/dandi/dandizarrs --backup-remote dandi-dandisets-dropbox --zarr-backup-remote dandi-dandizarrs-dropbox --gh-org dandisets --zarr-gh-org dandizarrs 000108
A newer version (0.40.1) of dandi/dandi-cli is available. You are using 0.40.0
2022-06-07T15:07:54-0400 [ERROR   ] backups2datalad sub-MITU01/ses-20210817h18m20s17/micr/sub-MITU01_ses-20210817h18m20s17_sample-120_stain-LEC_run-1_chunk-7_SPIM.json: download failed:   download failed: Internal Server Error
2022-06-07T15:15:20-0400 [WARNING ] backups2datalad Retrying GET request to https://api.dandiarchive.org/api/assets/3df2e285-9f33-4a1d-8751-413db2d46bd6/ in 1.000000 seconds as it raised ReadTimeout:
2022-06-07T15:15:47-0400 [WARNING ] backups2datalad Retrying GET request to https://api.dandiarchive.org/api/assets/3df2e285-9f33-4a1d-8751-413db2d46bd6/ in 1.800000 seconds as it raised ConnectTimeout:
2022-06-07T15:16:18-0400 [WARNING ] backups2datalad Retrying GET request to https://api.dandiarchive.org/api/assets/3df2e285-9f33-4a1d-8751-413db2d46bd6/ in 3.240000 seconds as it raised ConnectTimeout:
2022-06-07T15:16:48-0400 [WARNING ] backups2datalad Retrying GET request to https://api.dandiarchive.org/api/assets/3df2e285-9f33-4a1d-8751-413db2d46bd6/ in 5.832000 seconds as it raised ConnectTimeout:
2022-06-07T15:17:17-0400 [WARNING ] backups2datalad Retrying GET request to https://api.dandiarchive.org/api/assets/3df2e285-9f33-4a1d-8751-413db2d46bd6/ in 10.497600 seconds as it raised ConnectTimeout:
2022-06-07T15:17:54-0400 [WARNING ] backups2datalad Retrying GET request to https://api.dandiarchive.org/api/assets/3df2e285-9f33-4a1d-8751-413db2d46bd6/ in 18.895680 seconds as it raised ConnectTimeout:
2022-06-07T15:18:34-0400 [WARNING ] backups2datalad Retrying GET request to https://api.dandiarchive.org/api/assets/3df2e285-9f33-4a1d-8751-413db2d46bd6/ in 34.012224 seconds as it raised ConnectTimeout:
2022-06-07T15:19:25-0400 [WARNING ] backups2datalad Retrying GET request to https://api.dandiarchive.org/api/assets/3df2e285-9f33-4a1d-8751-413db2d46bd6/ in 61.222003 seconds as it raised ConnectTimeout:
2022-06-07T15:20:40-0400 [WARNING ] backups2datalad Retrying GET request to https://api.dandiarchive.org/api/assets/3df2e285-9f33-4a1d-8751-413db2d46bd6/ in 110.199606 seconds as it raised ConnectTimeout:
2022-06-07T15:21:45-0400 [WARNING ] backups2datalad git-annex whereis command exited with return code 1
add(ok): .dandi/s3sync.json (file)
add(ok): .dandi/zarr-checksum (file)
save(ok): . (dataset)
...
  create_sibling_github (ok: 1)
2022-06-07T15:35:18-0400 [ERROR   ] backups2datalad sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-NN_run-1_chunk-7_SPIM.json: download failed: git-annex: user error (xargs ["-0","git","--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","filter.annex.smudge=","-c","filter.annex.clean=","-c","filter.annex.process=","add","-f","--"] exited 123)
2022-06-07T15:35:18-0400 [ERROR   ] backups2datalad sub-MITU01/ses-20220311h10m19s37/micr/sub-MITU01_ses-20220311h10m19s37_sample-22_stain-LEC_run-1_chunk-4_SPIM.json: download failed: git-annex: user error (xargs ["-0","git","--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","filter.annex.smudge=","-c","filter.annex.clean=","-c","filter.annex.process=","add","-f","--"] exited 123)
2022-06-07T15:36:07-0400 [ERROR   ] backups2datalad sub-MITU01/ses-20220326h16m14s39/micr/sub-MITU01_ses-20220326h16m14s39_sample-6_stain-NN_run-1_chunk-4_SPIM.json: download failed: git-annex: user error (xargs ["-0","git","--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","filter.annex.smudge=","-c","filter.annex.clean=","-c","filter.annex.process=","add","-f","--"] exited 123)
2022-06-07T15:36:07-0400 [ERROR   ] backups2datalad sub-MITU01/ses-20220326h16m14s39/micr/sub-MITU01_ses-20220326h16m14s39_sample-6_stain-YO_run-1_chunk-1_SPIM.json: download failed: git-annex: user error (xargs ["-0","git","--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","filter.annex.smudge=","-c","filter.annex.clean=","-c","filter.annex.process=","add","-f","--"] exited 123)
2022-06-07T15:36:07-0400 [ERROR   ] backups2datalad sub-MITU01/ses-20220326h16m14s39/micr/sub-MITU01_ses-20220326h16m14s39_sample-6_stain-LEC_run-1_chunk-2_SPIM.json: download failed: git-annex: user error (xargs ["-0","git","--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","filter.annex.smudge=","-c","filter.annex.clean=","-c","filter.annex.process=","add","-f","--"] exited 123)
2022-06-07T15:36:07-0400 [ERROR   ] backups2datalad sub-MITU01/ses-20220326h16m14s39/micr/sub-MITU01_ses-20220326h16m14s39_sample-6_stain-NN_run-1_chunk-3_SPIM.json: download failed: git-annex: user error (xargs ["-0","git","--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","filter.annex.smudge=","-c","filter.annex.clean=","-c","filter.annex.process=","add","-f","--"] exited 123)
2022-06-07T15:36:08-0400 [ERROR   ] backups2datalad sub-MITU01/ses-20220326h16m14s39/micr/sub-MITU01_ses-20220326h16m14s39_sample-6_stain-LEC_run-1_chunk-1_SPIM.json: download failed: git-annex: user error (xargs ["-0","git","--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","filter.annex.smudge=","-c","filter.annex.clean=","-c","filter.annex.process=","add","-f","--"] exited 123)
2022-06-07T15:36:08-0400 [ERROR   ] backups2datalad sub-MITU01/ses-20220326h16m14s39/micr/sub-MITU01_ses-20220326h16m14s39_sample-6_stain-LEC_run-1_chunk-3_SPIM.json: download failed: git-annex: user error (xargs ["-0","git","--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","filter.annex.smudge=","-c","filter.annex.clean=","-c","filter.annex.process=","add","-f","--"] exited 123)
2022-06-07T15:41:47-0400 [WARNING ] backups2datalad git-annex whereis command exited with return code 1
add(ok): .dandi/s3sync.json (file)
add(ok): .dandi/zarr-checksum (file)
add(ok): .zgroup (file)
add(ok): .zmetadata (file)
add(ok): 0/.zarray (file)
save(ok): . (dataset)
action summary:
  add (ok: 5)
  save (ok: 1)   
                 Enumerating objects: 164578, done.
Counting objects: 100% (164578/164578), done.
Delta compression using up to 4 threads
Compressing objects: 100% (125836/125836), done.
Writing objects: 100% (164578/164578), done.
Total 164578 (delta 43553), reused 159710 (delta 38687), pack-reused 0
publish(ok): . (dataset) [refs/heads/draft->github:refs/heads/draft 7f5653935..aae4cb251]
publish(ok): . (dataset) [refs/heads/git-annex->github:refs/heads/git-annex 6762b863d..ea1485979]
action summary:
  publish (ok: 2)
create(ok): . (dataset)
add(ok): .dandi/.gitattributes (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
create_sibling_github(ok): [sibling repository 'github' created at https://github.com/dandizarrs/756c1ce7-a09c-4526-94c2-f26cc43fa702]
[INFO   ] Configure additional publication dependency on "dandi-dandizarrs-dropbox"
configure-sibling(ok): . (sibling)
action summary:
  configure-sibling (ok: 1)
  create_sibling_github (ok: 1)
                 2022-06-07T15:46:44-0400 [WARNING ] backups2datalad git-annex whereis command exited with return code 1
Total: 0.00 datasets [00:00, ? datasets/s]                                                                                                                                                                           2022-06-07T15:47:48-0400 [WARNING ] backups2datalad git-annex whereis command exited with return code 1
2022-06-07T15:47:55-0400 [WARNING ] backups2datalad git-annex whereis command exited with return code 1                                                                               | 0.00/195 [00:00<?, ? Bytes/s]
2022-06-07T15:47:57-0400 [WARNING ] backups2datalad git-annex whereis command exited with return code 1
add(ok): .dandi/s3sync.json (file)
...
[INFO   ] Configure additional publication dependency on "dandi-dandizarrs-dropbox"
configure-sibling(ok): . (sibling)
action summary:
  configure-sibling (ok: 1)
  create_sibling_github (ok: 1)
create_sibling_github(ok): [sibling repository 'github' created at https://github.com/dandizarrs/b6c08f74-9eca-4fe2-9c7a-ec0b88b3a1fb]
[INFO   ] Configure additional publication dependency on "dandi-dandizarrs-dropbox"
configure-sibling(ok): . (sibling)
action summary:
  configure-sibling (ok: 1)
  create_sibling_github (ok: 1)
create_sibling_github(ok): [sibling repository 'github' created at https://github.com/dandizarrs/8aa95fb1-b2ee-410a-85e8-3ffd51c2fa85]
[INFO   ] Configure additional publication dependency on "dandi-dandizarrs-dropbox"
configure-sibling(ok): . (sibling)
action summary:
  configure-sibling (ok: 1)
  create_sibling_github (ok: 1)
                 2022-06-07T16:07:42-0400 [WARNING ] backups2datalad git-annex whereis command exited with return code 1
2022-06-07T16:07:42-0400 [WARNING ] backups2datalad git-annex addurl command exited with return code 1
2022-06-07T16:07:42-0400 [ERROR   ] backups2datalad Operation failed with exception:
Traceback (most recent call last):
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/util.py", line 315, in dandi_logging
    yield logfile
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 144, in sync_dataset
    syncer.sync_assets()
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/syncer.py", line 36, in sync_assets
    self.report = anyio.run(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/asyncer.py", line 408, in async_assets
    nursery.start_soon(dm.read_addurl)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/zarr.py", line 433, in sync_zarr
    await anyio.run_process(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_core/_subprocesses.py", line 90, in run_process
    raise CalledProcessError(cast(int, process.returncode), command, output, errors)
subprocess.CalledProcessError: Command '['git', 'gc']' returned non-zero exit status 128.
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 389, in <module>
    main()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 172, in update_from_backup
    datasetter.update_from_backup(dandisets, exclude=exclude)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 77, in update_from_backup
    changed = self.sync_dataset(d, ds)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 144, in sync_dataset
    syncer.sync_assets()
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/syncer.py", line 36, in sync_assets
    self.report = anyio.run(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/asyncer.py", line 408, in async_assets
    nursery.start_soon(dm.read_addurl)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/zarr.py", line 433, in sync_zarr
    await anyio.run_process(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_core/_subprocesses.py", line 90, in run_process
    raise CalledProcessError(cast(int, process.returncode), command, output, errors)
subprocess.CalledProcessError: Command '['git', 'gc']' returned non-zero exit status 128.
```

so it is that problematic case with some errors from #168 but then at the end `git gc` erroring out entirely. Something must be not really kosher while invoking that command

**Comment by yarikoptic** [comment]
in current crash I spotted

```
fatal: gc is already running on machine 'drogon' pid 638313 (use --force if not)
2022-06-07T22:17:30-0400 [WARNING ] backups2datalad git-annex addurl command exited with return code 1
2022-06-07T22:17:30-0400 [ERROR   ] backups2datalad Operation failed with exception:
...
subprocess.CalledProcessError: Command '['git', 'gc']' returned non-zero exit status 128.
```
so let's just assume that exit 128 is because another `gc` is running, and "let it be".  

@jwodder please centralize calling `gc` since we have two spots already
```
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets/tools/backups2datalad$ git grep 'git.*gc'
datasetter.py:            log.debug("Running `git gc`")
datasetter.py:            subprocess.run(["git", "gc"], cwd=ds.path, check=True)
datasetter.py:            log.debug("Finished running `git gc`")
zarr.py:            log.debug("Zarr %s: Running `git gc`", asset.zarr)
zarr.py:                ["git", "gc"], cwd=ds.path, stdout=None, stderr=None
zarr.py:            log.debug("Zarr %s: Finished running `git gc`", asset.zarr)
```
and ignore 128 while reporting in which dataset it happened (path).
