### ISSUE TITLE
--dbg  CLI option using epdb to troubleshoot interactively 

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#193]
with all the async -- how could we add some `--dbg` similar to the one we have in dandi-cli, datalad etc to end up at the point of the exception to troubleshoot it ?  now it is hard to impossible to figure out what wrong is going on in e.g. #168 .

I think we could do it via  `epdb`  see https://github.com/datalad/datalad/blob/master/CONTRIBUTING.md#useful-tools ...  

<details>
<summary>might need to sweep through a few ports to find an available one</summary> 

```shell
$> python3 -c 'import epdb; epdb.serve()'
Serving on port 8080
^Z
[1]  + 447112 suspended  python3 -c 'import epdb; epdb.serve()'
(dev3) 1 30197 ->148 [1].....................................:Tue 07 Jun 2022 05:21:27 PM EDT:.
(git)lena:~datalad/datalad-master[bf-push-github]
$> bg
[1]  + 447112 continued  python3 -c 'import epdb; epdb.serve()'
changes on filesystem:                                                                              
 datalad/local/foreach_dataset.py | 1 +
(dev3) 1 30198 [1].....................................:Tue 07 Jun 2022 05:21:28 PM EDT:.
(git)lena:~datalad/datalad-master[bf-push-github]
$> python3 -c 'import epdb; epdb.serve()'
Serving on port 8080
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev3/lib/python3.9/site-packages/epdb/__init__.py", line 1084, in serve
    Epdb().serve(port)
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev3/lib/python3.9/site-packages/epdb/__init__.py", line 149, in serve
    Epdb._server = epdb_server.InvertedTelnetServer(('', port))
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev3/lib/python3.9/site-packages/epdb/epdb_server.py", line 216, in __init__
    TelnetServer.__init__(self, server_address, requestHandlerClass)
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev3/lib/python3.9/site-packages/epdb/epdb_server.py", line 163, in __init__
    TCPServer.__init__(self, server_address, requestHandlerClass)
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

```
</details>

and report to user to which port to connect with epdb client.

Any other workable idea would also be welcome!

**Comment by yarikoptic** [comment]
oh , we already have `--pdb` !  I should try that first although really doubt it would work

edit: `--pdb` did work and I ended up at some exception ... but it seems (#194 ) that currently interesting to me places do not even raise exception

**Comment by yarikoptic** [comment]
re option -- we have it so I will close
