### ISSUE TITLE
might want versioned pydantic

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#227]
run failed and I had to upgrade pydantic

```
(base) dandi@drogon:/mnt/backup/dandi/dandisets$ flock -E 0 -e -n /home/dandi/.run/backup2datalad-cron.lock  /mnt/backup/dandi/dandisets/tools/backups2datalad-update-cron

>> python -m tools.backups2datalad -l WARNING --backup-root /mnt/backup/dandi --config tools/backups2datalad.cfg.yaml update-from-backup --workers 5 -e '000108$'
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 15, in <module>
    from .adandi import AsyncDandiClient
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/adandi.py", line 12, in <module>
    from dandi.dandiapi import DandiAPIClient, RemoteAsset
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/dandi/dandiapi.py", line 34, in <module>
    from dandischema import models
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/dandischema/__init__.py", line 2, in <module>
    from .metadata import migrate, validate
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/dandischema/metadata.py", line 17, in <module>
    from . import models
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/dandischema/models.py", line 10, in <module>
    from pydantic import (
ImportError: cannot import name 'UUID4' from 'pydantic' (unknown location)
(base) dandi@drogon:/mnt/backup/dandi/dandisets$
(reverse-i-search)`': ^C
(base) dandi@drogon:/mnt/backup/dandi/dandisets$ conda activate dandisets
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets$ conda update -c conda-forge pydantic

PackageNotInstalledError: Package is not installed in prefix.
  prefix: /home/dandi/miniconda3/envs/dandisets
  package name: pydantic


(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets$ pip install --upgrade pydantic
Requirement already satisfied: pydantic in /home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages (1.9.0)
Collecting pydantic
  Downloading pydantic-1.9.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 23.3 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages (from pydantic) (4.2.0)
Installing collected packages: pydantic
  Attempting uninstall: pydantic
    Found existing installation: pydantic 1.9.0
    Uninstalling pydantic-1.9.0:
      Successfully uninstalled pydantic-1.9.0
Successfully installed pydantic-1.9.1
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets$ flock -E 0 -e -n /home/dandi/.run/backup2datalad-cron.lock  /mnt/backup/dandi/dandisets/tools/backups2datalad-update-cron
>> python -m tools.backups2datalad -l WARNING --backup-root /mnt/backup/dandi --config tools/backups2datalad.cfg.yaml update-from-backup --workers 5 -e '000108$'
2022-07-18T10:31:48-0400 [WARNING ] dandi: A newer version (0.45.1) of dandi/dandi-cli is available. You are using 0.40.0
action summary:
  publish (notneeded: 2)
action summary:
  publish (notneeded: 2)
action summary:
  publish (notneeded: 2)
action summary:
  publish (notneeded: 2)
action summary:
  publish (notneeded: 2)
action summary:
  publish (notneeded: 2)
action summary:
...
```

we have

```
$> git grep pydantic.*= -- tools
tools/backups2datalad.req.txt:pydantic ~= 1.8
tools/get-upload-stats.req.txt:pydantic ~= 1.7
```

should those be updated to `~= 1.9`?

**Comment by jwodder** [comment]
@yarikoptic Pydantic appears to have had UUID4 since v0.9.1; increasing the version shouldn't be necessary.  If it is necessary, the proper place to change it would be in dandischema, as that's what's importing pydantic.UUID4.

**Comment by yarikoptic** [comment]
> @yarikoptic Pydantic appears to have had UUID4 since v0.9.1;

did you mean 1.9.1 since I upgraded from 1.9.0 to 1.9.1?

if you feel that it needs to be done in dandischema -- please send a PR against it. But then how can we require `pydantic ~= 1.8` if we would need `>= 1.9.1` through dandischema -- would need to be updated too, right? (edit: I mean - please send needed PRs to ensure robust operation of the tandem here)

**Comment by jwodder** [comment]
@yarikoptic No, I meant [0.9.1](https://pydantic-docs.helpmanual.io/changelog/#v091-2018-05-10).  I don't really know what caused the original issue, but I don't think it was simply pydantic being out of date.

**Comment by yarikoptic** [comment]
ah, ok.  That "unknown location" in the original error hints that may be somehow installation got screwed up. Ok, let's consider it an installation fluke we cannot anyhow address.
