### ISSUE TITLE
000026 history got split

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#230]
like there was a commit with partial changes pushed... may be that is what happened, but now we have on github a commit with some files missing from what we have on drogon, although commit message and date are identical

On drogon:
```
(git-annex)lena:~/proj/dandi/dandisets/000026[draft]
$> git show drogon/draft | head
commit 2ba6cea0d0d8f997448c6630a664252caba5f4a1
Author: DANDI User <info@dandiarchive.org>
Date:   Fri Jul 22 07:13:23 2022 +0000

    [backups2datalad] 39814 files added

diff --git a/dataset_description.json b/dataset_description.json
new file mode 100644
index 0000000000..7cf8d6b9d9
--- /dev/null

$> git show drogon/draft | diffstat | nl | tail
 30829	 sub-I48/ses-SPIM/micr/sub-I48_ses-SPIM_sample-BrocaAreaS23_stain-NeuN_chunk-04_SPIM.ome.tif         |    1 
 30830	 sub-I48/ses-SPIM/micr/sub-I48_ses-SPIM_sample-BrocaAreaS23_stain-NeuN_chunk-05_SPIM.json            |   51 ++++++
 30831	 sub-I48/ses-SPIM/micr/sub-I48_ses-SPIM_sample-BrocaAreaS23_stain-NeuN_chunk-05_SPIM.ome.tif         |    1 
 30832	 sub-I48/ses-SPIM/micr/sub-I48_ses-SPIM_sample-BrocaAreaS23_stain-NeuN_chunk-06_SPIM.json            |   51 ++++++
 30833	 sub-I48/ses-SPIM/micr/sub-I48_ses-SPIM_sample-BrocaAreaS23_stain-NeuN_chunk-06_SPIM.ome.tif         |    1 
 30834	 sub-I48/ses-SPIM/micr/sub-I48_ses-SPIM_sample-BrocaAreaS23_stain-NeuN_chunk-07_SPIM.json            |   51 ++++++
 30835	 sub-I48/ses-SPIM/micr/sub-I48_ses-SPIM_sample-BrocaAreaS23_stain-NeuN_chunk-07_SPIM.ome.tif         |    1 
 30836	 sub-I48/ses-SPIM/micr/sub-I48_ses-SPIM_sample-BrocaAreaS23_stain-NeuN_chunk-08_SPIM.json            |   51 ++++++
 30837	 sub-I48/ses-SPIM/micr/sub-I48_ses-SPIM_sample-BrocaAreaS23_stain-NeuN_chunk-08_SPIM.ome.tif         |    1 
 30838	 30837 files changed, 793037 insertions(+)
```
so talks about 39814 additions and stat shows only 30838 (also odd!)

on origin (github) it is even less committed

```
$> git show origin/draft | head                
commit 0469a389b17abd64e0e0c2bea829dcea11e71420
Author: DANDI User <info@dandiarchive.org>
Date:   Fri Jul 22 07:13:23 2022 +0000

    [backups2datalad] 39814 files added

diff --git a/dataset_description.json b/dataset_description.json
new file mode 100644
index 0000000000..7cf8d6b9d9
--- /dev/null

$> git show origin/draft | diffstat | nl | tail
 10271	 sub-I38/ses-SPIM/micr/sub-I38_ses-SPIM_sample-BrocaAreaS26_stain-Somatostatin_chunk-04_SPIM.ome.tif |    1 
 10272	 sub-I38/ses-SPIM/micr/sub-I38_ses-SPIM_sample-BrocaAreaS26_stain-Somatostatin_chunk-05_SPIM.json    |   51 ++++++
 10273	 sub-I38/ses-SPIM/micr/sub-I38_ses-SPIM_sample-BrocaAreaS26_stain-Somatostatin_chunk-05_SPIM.ome.tif |    1 
 10274	 sub-I38/ses-SPIM/micr/sub-I38_ses-SPIM_sample-BrocaAreaS26_stain-Somatostatin_chunk-06_SPIM.json    |   51 ++++++
 10275	 sub-I38/ses-SPIM/micr/sub-I38_ses-SPIM_sample-BrocaAreaS26_stain-Somatostatin_chunk-06_SPIM.ome.tif |    1 
 10276	 sub-I38/ses-SPIM/micr/sub-I38_ses-SPIM_sample-BrocaAreaS26_stain-Somatostatin_chunk-07_SPIM.json    |   51 ++++++
 10277	 sub-I38/ses-SPIM/micr/sub-I38_ses-SPIM_sample-BrocaAreaS26_stain-Somatostatin_chunk-07_SPIM.ome.tif |    1 
 10278	 sub-I38/ses-SPIM/micr/sub-I38_ses-SPIM_sample-BrocaAreaS26_stain-Somatostatin_chunk-08_SPIM.json    |   51 ++++++
 10279	 sub-I38/ses-SPIM/micr/sub-I38_ses-SPIM_sample-BrocaAreaS26_stain-Somatostatin_chunk-08_SPIM.ome.tif |    1 
 10280	 10279 files changed, 264491 insertions(+)
```

so clearly it is even more "incomplete".  But another aspect that neither reflect any removals!  And all those files were moved in the archive from `rawdata/`.

@jwodder - any clues on what might be going on? count doesn't match, deletions are not reflected.

PS if we are to redo, we might want better first upgrade to v9 or v10 of the repo (#229 )

**Comment by yarikoptic** [comment]
oh, since cron job was not disabled (I was reacting to email about failed push), backup script is already running and current status of the repo is

```
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets/000026$ git status | grep 'new file' | nl | tail
  8968          new file:   sub-KC001/ses-MRI/anat/sub-KC001_ses-MRI_echo-2_flip-4_VFA.nii.gz
  8969          new file:   sub-KC001/ses-MRI/anat/sub-KC001_ses-MRI_echo-3_flip-1_VFA.nii.gz
  8970          new file:   sub-KC001/ses-MRI/anat/sub-KC001_ses-MRI_echo-3_flip-2_VFA.nii.gz
  8971          new file:   sub-KC001/ses-MRI/anat/sub-KC001_ses-MRI_echo-3_flip-3_VFA.nii.gz
  8972          new file:   sub-KC001/ses-MRI/anat/sub-KC001_ses-MRI_echo-3_flip-4_VFA.nii.gz
  8973          new file:   sub-KC001/ses-MRI/anat/sub-KC001_ses-MRI_echo-4_flip-1_VFA.nii.gz
  8974          new file:   sub-KC001/ses-MRI/anat/sub-KC001_ses-MRI_echo-4_flip-2_VFA.nii.gz
  8975          new file:   sub-KC001/ses-MRI/anat/sub-KC001_ses-MRI_echo-4_flip-3_VFA.nii.gz
  8976          new file:   sub-KC001/ses-MRI/anat/sub-KC001_ses-MRI_echo-4_flip-4_VFA.nii.gz
  8977          new file:   sub-KC001/sub-KC001_sessions.tsv
```

**Comment by yarikoptic** [comment]
FWIW, disabled cron job for now

**Comment by jwodder** [comment]
@yarikoptic I'm stumped.  I can confirm that the old `rawdata/` paths are still listed in `000026/.dandi/assets.json`, and I can confirm that the function for listing the assets in a DataLad backup returns the `rawdata/` assets for 000026.  I can also confirm via the backup logs that the server stopped listing the `rawdata/` assets for 000026 on the 21st.  These things together mean that `rawdata/` *should* have been deleted by now.  The only possible reasons why it wouldn't that I can come up with would be if (a) the wrong path was passed to the local-asset-listing function, but that would be accompanied by other problems, or (b) the `prune_deleted()` function wasn't called, but that should only happen if an error occurred before then; I can see that two errors occurred with 000026 on the 21st (due to an HTTP request to Dandi Archive repeatedly timing out), but the runs after that didn't error, and they should have deleted `rawdata/` just fine.

**Comment by yarikoptic** [comment]
I might know what it could be although not 100% certain.  Might relate to datalad needing to split a single `commit` into multiple while having too many entries given in the command line! https://github.com/datalad/datalad/blob/master/datalad/support/gitrepo.py#L1409  so we could end up with a commit stating some large number of files being committed but then "not". Then subsequent `commit` invocation needs to `--amend` it with more files  And now I see that we are running `git -c diff.ignoreSubmodules=none commit -m "[backups2datalad] 39814 files added" --amend --no-edit -- ...` but how we managed to push that "yet to be amended" state? that I don't know.

I am running similar `datalad save` on falkor (since yesterday!!!) -- may be we will see what would happen there. So far looks like this

```
falkor:/tmp/000026
$> git reflog
d1f7ec122c (HEAD -> draft) HEAD@{0}: commit (amend): commit all
734fff1adb HEAD@{1}: commit (amend): commit all
6ff42e007a HEAD@{2}: commit: commit all
a10eb57d8b (origin/draft, origin/HEAD) HEAD@{3}: clone: from /tmp/000026-reference

*$> git log -n 3
commit d1f7ec122ca1116555a32870fe0986bdd392afdc (HEAD -> draft)
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Sun Jul 24 21:11:01 2022 -0400

    commit all

commit a10eb57d8b473344f43ec39223e21245c8f83adc (origin/draft, origin/HEAD)
Author: DANDI User <info@dandiarchive.org>
Date:   Fri Jul 1 17:45:34 2022 +0000

    [backups2datalad] 1 file deleted
```

I think I will wait for current backup run on 000026 to complete, then migrate it to v10 of repo, and if we see no deletions performed, will give it back to you to troubleshoot that aspect.

**Comment by yarikoptic** [comment]
or may be screw it -- current behavior/performance is so bad that I will just kill, hard reset to the state before the move, upgrade to v9, and redo backup!

**Comment by yarikoptic** [comment]
it managed to commit additions nicely, 

<details>
<summary>but it crashed on removals with following</summary> 

```
...
rm 'rawdata/sub-I38/ses-SPIM/micr/sub-I38_ses-SPIM_sample-BrocaAreaS48_stain-Calretinin_chunk-32_SPIM.ome.tif'
rm 'rawdata/sub-I48/ses-SPIM/micr/sub-I48_ses-SPIM_sample-BrocaAreaS37_stain-NeuN_chunk-00_SPIM.json'
fatal: Unable to create '/mnt/backup/dandi/dandisets/000026/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
2022-07-25T21:37:27-0400 [ERROR   ] backups2datalad: Job failed on input <Dandiset 000026/draft>:
Traceback (most recent call last):
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/aioutil.py", line 189, in dowork
    outp = await func(inp)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 136, in update_dandiset
    changed, zarr_stats = await self.sync_dataset(dandiset, ds, dmanager)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 160, in sync_dataset
    await syncer.prune_deleted()
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/syncer.py", line 52, in prune_deleted
    await self.ds.remove(asset_path)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/adataset.py", line 178, in remove
    await self.call_git("rm", path)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/adataset.py", line 110, in call_git
    await aruncmd("git", *args, cwd=self.path, **kwargs)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/aioutil.py", line 218, in aruncmd
    return await anyio.run_process(argstrs, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_core/_subprocesses.py", line 90, in run_process
    raise CalledProcessError(cast(int, process.returncode), command, output, errors)
subprocess.CalledProcessError: Command '['git', 'rm', 'rawdata/sub-I48/ses-SPIM/micr/sub-I48_ses-SPIM_sample-BrocaAreaS06_stain-NeuN_chunk-01_SPIM.ome.tif']' returned non-zero exit status 128.
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 414, in <module>
    main(_anyio_backend="asyncio")
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/asyncclick/core.py", line 1157, in __call__
    return anyio.run(self._main, main, args, kwargs, **opts)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/asyncclick/core.py", line 1160, in _main
    return await main(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/asyncclick/core.py", line 1076, in main
    rv = await self.invoke(ctx)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/asyncclick/core.py", line 1687, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/asyncclick/core.py", line 1434, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/asyncclick/core.py", line 780, in invoke
    rv = await rv
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 136, in update_from_backup
    await datasetter.update_from_backup(dandisets, exclude=exclude)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 97, in update_from_backup
    raise RuntimeError(
RuntimeError: Backups for 15 Dandisets failed
```

</details>

I am not sure what processes conflicted (may be some `git gc`?) or may be it was multiple `git rm` invocations - does it do it per file @jwodder judging from `CalledProcessError` above? then better collect all and run in a single invocation to `git rm` (but may be through datalad's `_call_git` so it batches it). I have left `git rm -r rawdata/` run in a screen.  Then next would be to "commit" with the correct date/authorship of the prior commit.  What would be the best way to do that?

**Comment by yarikoptic** [comment]
well, did `git commit --amend -C 45b0c90db71f7682a57a55a27b537ae8fd51f628` and it seems picked up the commit date etc from prior one. now only we have a bit misleading commit message since those were not added but moved.

I have done `git gc --prune=now` to bring .git/objects down (not much -- still 192M from some 200M), and then restarted the backup job in the screen to see if we arrive clean.

**Comment by yarikoptic** [comment]
oh hoh... I hit Enter too early.  `git push -f` for 000026 failed now with

```
(dandi-cli-latest) dandi@drogon:/mnt/backup/dandi/dandisets/000026$ git push -f
Enumerating objects: 34612, done.
Counting objects: 100% (34612/34612), done.
Delta compression using up to 4 threads
Compressing objects: 100% (21286/21286), done.
Writing objects: 100% (34609/34609), 7.80 MiB | 1.90 MiB/s, done.
Total 34609 (delta 14505), reused 33348 (delta 13290), pack-reused 0
remote: Resolving deltas: 100% (14505/14505), completed with 1 local object.
remote: error: Trace: 06e2efc699041b66cb47348459b7cb1c9e5d3f94761623ec6adfccb5e16d7d9a
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File .dandi/assets.json is 131.89 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To github.com:dandisets/000026.git
 ! [remote rejected]       draft -> draft (pre-receive hook declined)
error: failed to push some refs to 'github.com:dandisets/000026.git'
```

damn github and the gotcha is that actually that file does still contain entries for `rawdata/` files which I have manually removed... I will try rerunning backup script to see if it manages somehow to fix up the situation but it might be needing manually cleansing.

**Comment by yarikoptic** [comment]
overall this issue is resolved. It was due to `datalad save` needing to do multiple commits with `--amend` for a long list of paths
