### ISSUE TITLE
feed_data after feed_eof

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#260]
Having #258 merged and trying to update 000108 we get 

```
python -m tools.backups2datalad -l INFO --backup-root /mnt/backup/dandi --config tools/backups2datalad.cfg.yaml update-from-backup --workers 5  000108
```

crashing with (pasting relevant from the log, not what was on the screen)

```
2022-09-08T14:58:35-0400 [DEBUG   ] backups2datalad: Dandiset 000108: Zarr 924410ea-f204-4559-930c-d77677b82a92: Creating GitHub sibling
2022-09-08T14:58:35-0400 [DEBUG   ] backups2datalad: Running: git remote [cwd=/mnt/backup/dandi/dandizarrs/924410ea-f204-4559-930c-d77677b82a92]
2022-09-08T14:58:35-0400 [DEBUG   ] backups2datalad: Waiting for `git-annex find '--include=*' --json` [cwd=/mnt/backup/dandi/dandizarrs/192e6322-1ef1-4d2a-ad3a-deded1b9eeae] to terminate
2022-09-08T14:58:35-0400 [DEBUG   ] backups2datalad: Waiting for `git-annex find '--include=*' --json` [cwd=/mnt/backup/dandi/dandizarrs/b353116e-e7ed-459c-8e01-5d770b6561eb] to terminate
2022-09-08T14:58:35-0400 [DEBUG   ] backups2datalad: Waiting for `git-annex find '--include=*' --json` [cwd=/mnt/backup/dandi/dandizarrs/e005d98a-1405-40a7-aaa8-5be18bfa9e40] to terminate
2022-09-08T14:58:35-0400 [DEBUG   ] backups2datalad: Waiting for `git-annex find '--include=*' --json` [cwd=/mnt/backup/dandi/dandizarrs/85e1e97e-d5db-47ab-9683-43b6595736a3] to terminate
2022-09-08T14:58:35-0400 [DEBUG   ] backups2datalad: Waiting for `git-annex find '--include=*' --json` [cwd=/mnt/backup/dandi/dandizarrs/68d332a6-f81f-491e-bdff-4064b0eba08f] to terminate
2022-09-08T14:58:35-0400 [DEBUG   ] backups2datalad: Waiting for `git-annex find '--include=*' --json` [cwd=/mnt/backup/dandi/dandizarrs/d4bcfa6f-3c37-48d1-8b22-9bff34d15c6f] to terminate
2022-09-08T14:58:35-0400 [DEBUG   ] backups2datalad: Waiting for `git-annex find '--include=*' --json` [cwd=/mnt/backup/dandi/dandizarrs/0d72667e-2358-4159-a355-a3fc521d7278] to terminate
2022-09-08T14:58:35-0400 [DEBUG   ] backups2datalad: Waiting for `git-annex find '--include=*' --json` [cwd=/mnt/backup/dandi/dandizarrs/03cf98fe-0e9c-4180-bfa6-f1b4ef9471d3] to terminate
2022-09-08T14:58:35-0400 [DEBUG   ] backups2datalad: Waiting for `git-annex find '--include=*' --json` [cwd=/mnt/backup/dandi/dandizarrs/4c6df528-58d8-472f-a3e2-ac792d266b07] to terminate
2022-09-08T14:58:35-0400 [ERROR   ] asyncio: Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b'db9582fc5a7...   135\t0/0/0')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'db9582fc5a7...   135\t0/0/0')>
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/subprocess.py", line 73, in pipe_data_received
    reader.feed_data(data)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/streams.py", line 472, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
2022-09-08T14:58:35-0400 [ERROR   ] asyncio: Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b'/0/3/10/23\.../0/21\x000/0/')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'/0/3/10/23\.../0/21\x000/0/')>
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/subprocess.py", line 73, in pipe_data_received
    reader.feed_data(data)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/streams.py", line 472, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
2022-09-08T14:58:35-0400 [ERROR   ] asyncio: Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b'c7476019728...    135\t0/0/')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'c7476019728...    135\t0/0/')>
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/subprocess.py", line 73, in pipe_data_received
    reader.feed_data(data)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/streams.py", line 472, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
... many more like that ...
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/subprocess.py", line 73, in pipe_data_received
    reader.feed_data(data)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/streams.py", line 472, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
2022-09-08T14:58:37-0400 [DEBUG   ] backups2datalad: Command `git-annex registerurl -c annex.alwayscompact=false --batch --json --json-error-messages` [cwd=/mnt/backup/dandi/dandisets/000108] exited with return code 0
2022-09-08T14:58:37-0400 [DEBUG   ] backups2datalad: Waiting for `git-annex addurl -c annex.alwayscompact=false --batch --with-files --jobs 5 --json --json-error-messages --json-progress --raw` [cwd=/mnt/backup/dandi/dandisets/000108] to terminate
2022-09-08T14:58:37-0400 [DEBUG   ] backups2datalad: Command `git-annex addurl -c annex.alwayscompact=false --batch --with-files --jobs 5 --json --json-error-messages --json-progress --raw` [cwd=/mnt/backup/dandi/dandisets/000108] exited with return code 0
2022-09-08T14:58:39-0400 [ERROR   ] backups2datalad: Job failed on input <Dandiset 000108/draft>:
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpcore/backends/asyncio.py", line 101, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError

... more crashes etc...
```

full log at /mnt/backup/dandi/dandisets/.git/dandi/backups2datalad/2022.09.08.18.27.28Z.log  and somewhat cleaned up (no boto etc) is at /mnt/backup/dandi/dandisets/.git/dandi/backups2datalad/2022.09.08.18.27.28Z_filt.log .

@jwodder what this could be due to?

**Comment by jwodder** [comment]
@yarikoptic My best guess is that an exception is occurring in [this block](https://github.com/dandi/dandisets/blob/ae17e4e1032f93a9119d468c7edb356902842a0c/tools/backups2datalad/adataset.py#L197-L200), after which the stdout of the `git-annex find` process is closed while it's still outputting data, but I would expect that to be handled better.  Try running the code again with the following patch and seeing if an additional exception gets logged:

```diff
diff --git a/tools/backups2datalad/adataset.py b/tools/backups2datalad/adataset.py
index 7c22087..b085fd5 100644
--- a/tools/backups2datalad/adataset.py
+++ b/tools/backups2datalad/adataset.py
@@ -194,10 +194,14 @@ class AsyncDataset:
         async with await open_git_annex(
             "find", "--include=*", "--json", use_stdin=False, path=self.pathobj
         ) as p:
-            async for line in p:
-                data = json.loads(line)
-                path = cast(str, data["file"])
-                filedict[path] = replace(filedict[path], size=int(data["bytesize"]))
+            try:
+                async for line in p:
+                    data = json.loads(line)
+                    path = cast(str, data["file"])
+                    filedict[path] = replace(filedict[path], size=int(data["bytesize"]))
+            except Exception:
+                log.exception("Error parsing `git-annex find` output for %s:", self.path)
+                raise
         return list(filedict.values())
 
     async def create_github_sibling(
```

**Comment by yarikoptic** [comment]
pushed as 45a46eff4b65551ee632c35d24c9c2c62818688d and will try.  But not sure if we would see that exact problem right away since upon rerun I got another non-decypherable crash I am about to report details of.

**Comment by yarikoptic** [comment]
re-ran after #261 with the patch, there is no hits in the log for it (`grep 'Error parsing' 2022.09.09.*` is empty) and we get again LOTS of 

```
2022-09-09T10:05:18-0400 [INFO    ] backups2datalad: Dandiset 000108: Zarr 6a730749-ae68-4887-a1b5-d39aa548ed5f: backup up to date
2022-09-09T10:05:18-0400 [DEBUG   ] backups2datalad: Waiting for `git-annex find '--include=*' --json` [cwd=/mnt/backup/dandi/dandizarrs/66dbcc6f-0396-441d-aea6-0af8d5500562] to terminate
2022-09-09T10:05:18-0400 [DEBUG   ] backups2datalad: Waiting for `git-annex find '--include=*' --json` [cwd=/mnt/backup/dandi/dandizarrs/f7e3a560-c4a6-4652-b8c8-66afe580e4cb] to terminate
2022-09-09T10:05:18-0400 [ERROR   ] asyncio: Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b'42958772493...00 blob db9f0')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'42958772493...00 blob db9f0')>
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/subprocess.py", line 73, in pipe_data_received
    reader.feed_data(data)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/streams.py", line 472, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
2022-09-09T10:05:18-0400 [ERROR   ] asyncio: Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b' 3c70700699...4c3a8901b0ce0')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b' 3c70700699...4c3a8901b0ce0')>
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/subprocess.py", line 73, in pipe_data_received
    reader.feed_data(data)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/streams.py", line 472, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
...
```

full log `2022.09.09.13.53.32Z.log` .

<details>
<summary>and it seems to be at the end the repetition of such blocks of exception tracking</summary> 

```shell
2022-09-09T10:05:20-0400 [ERROR   ] asyncio: Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b'85e30ebce88...67b28487     ')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'85e30ebce88...67b28487     ')>
Traceback (most recent call last):
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 157, in update_from_backup
    await datasetter.update_from_backup(dandisets, exclude=exclude)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 98, in update_from_backup
    raise RuntimeError(
RuntimeError: Backups for 1 Dandiset failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/asyncclick/core.py", line 1160, in _main
    return await main(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/asyncclick/core.py", line 1076, in main
    rv = await self.invoke(ctx)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/asyncclick/core.py", line 1687, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/asyncclick/core.py", line 1434, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/asyncclick/core.py", line 780, in invoke
    rv = await rv
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 157, in update_from_backup
    await datasetter.update_from_backup(dandisets, exclude=exclude)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/abc/_resources.py", line 25, in __aexit__
    await self.aclose()
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 66, in aclose
    await self.manager.aclose()
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/manager.py", line 32, in aclose
    await self.gh.aclose()
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/manager.py", line 94, in aclose
    await self.client.aclose()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_client.py", line 1946, in aclose
    await self._transport.aclose()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_transports/default.py", line 365, in aclose
    await self._pool.aclose()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 312, in aclose
    raise RuntimeError(
RuntimeError: The connection pool was closed while 6 HTTP requests/responses were still in-flight.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/subprocess.py", line 73, in pipe_data_received
    reader.feed_data(data)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/streams.py", line 472, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
2022-09-09T10:05:20-0400 [ERROR   ] asyncio: Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b'    135\t0/...t0/0/0/11/0/2')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'    135\t0/...t0/0/0/11/0/2')>
Traceback (most recent call last):
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 157, in update_from_backup
    await datasetter.update_from_backup(dandisets, exclude=exclude)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 98, in update_from_backup
    raise RuntimeError(
RuntimeError: Backups for 1 Dandiset failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/asyncclick/core.py", line 1160, in _main
    return await main(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/asyncclick/core.py", line 1076, in main
    rv = await self.invoke(ctx)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/asyncclick/core.py", line 1687, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/asyncclick/core.py", line 1434, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/asyncclick/core.py", line 780, in invoke
    rv = await rv
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/__main__.py", line 157, in update_from_backup
    await datasetter.update_from_backup(dandisets, exclude=exclude)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/abc/_resources.py", line 25, in __aexit__
    await self.aclose()
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 66, in aclose
    await self.manager.aclose()
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/manager.py", line 32, in aclose
    await self.gh.aclose()
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/manager.py", line 94, in aclose
    await self.client.aclose()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_client.py", line 1946, in aclose
    await self._transport.aclose()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_transports/default.py", line 365, in aclose
    await self._pool.aclose()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 312, in aclose
    raise RuntimeError(
RuntimeError: The connection pool was closed while 6 HTTP requests/responses were still in-flight.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/subprocess.py", line 73, in pipe_data_received
    reader.feed_data(data)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/asyncio/streams.py", line 472, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof

```
</details>

suggesting that for all (?) of those the "main" exception is the `RuntimeError: Backups for 1 Dandiset failed` -- we can't hit that line multiple times ,right ?

**Comment by jwodder** [comment]
@yarikoptic On closer inspection, I think the initial error may be happening in the block above.  Try this patch:

```diff
diff --git a/tools/backups2datalad/adataset.py b/tools/backups2datalad/adataset.py
index d6c40b9..b91332f 100644
--- a/tools/backups2datalad/adataset.py
+++ b/tools/backups2datalad/adataset.py
@@ -189,7 +189,11 @@ class AsyncDataset:
             stream_null_command("git", "ls-tree", "-lrz", "HEAD", cwd=self.pathobj)
         ) as p:
             async for entry in p:
-                fst = FileStat.from_entry(entry)
+                try:
+                    fst = FileStat.from_entry(entry)
+                except Exception:
+                    log.exception("Error parsing ls-tree line %r for %s:", entry, self.path)
+                    raise
                 filedict[fst.path] = fst
         async with await open_git_annex(
             "find", "--include=*", "--json", use_stdin=False, path=self.pathobj
```

**Comment by yarikoptic** [comment]
FWIW -- running with that patch now, it seems to run for quite a while now without crashing... I will report whenever it completes one way or another

**Comment by yarikoptic** [comment]
ok, it crashed. (filtered a bit from foreign logs) log is at /mnt/backup/dandi/dandisets/.git/dandi/backups2datalad/2022.09.12.13.46.43Z_filt.log . `grep 'Error parsing' $PWD/2022.09.12.13.46.43Z_filt.log` comes out empty. Full of those `AssertionError: feed_data after feed_eof`. But those errors were preceeded with bunch of other errors

```shell
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets/.git/dandi/backups2datalad$ grep 'Error: ' $PWD/2022.09.12.13.46.43Z_filt.log | head
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://dandiarchive.s3.amazonaws.com/?list-type=2&prefix=zarr%2Ff4fa5830-f449-4cc8-8f83-30944b36b20b%2F&continuation-token=1buSENSORED&encoding-type=url".
...
```
and I do not see any of Retry logs for sample one of those urls (ref #261):

```
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets/.git/dandi/backups2datalad$ grep 'dandiarchive.s3.amazonaws.com/?list-type=2&prefix=zarr%2Ff4fa5830-f449-4cc8' $PWD/2022.09.12.13.46.43Z_filt.log
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://dandiarchive.s3.amazonaws.com/?list-type=2&prefix=zarr%2Ff4fa5830-f449-4cc8-8f83-30944b36b20b%2F&continuation-token=1buSENSORED&encoding-type=url".
```

**Comment by yarikoptic** [comment]
FWIW those ConnectionClosedError are likely 'red haring' since that sample closed connection is retried:

```
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets/.git/dandi/backups2datalad$ grep '//dandiarchive.s3.amazonaws.com/?list-type=2&prefix=zarr%2Ff4fa5830-f449-4cc8-8f83-30944b36b20b%2F&continuation-token=SENSORED&encoding-type=url' $PWD/2022.09.12.13.46.43Z.log
2022-09-12T10:16:39-0400 [DEBUG   ] botocore.utils: URI updated to: https://dandiarchive.s3.amazonaws.com/?list-type=2&prefix=zarr%2Ff4fa5830-f449-4cc8-8f83-30944b36b20b%2F&continuation-token=SENSORED&encoding-type=url
2022-09-12T10:16:39-0400 [DEBUG   ] botocore.endpoint: Sending http request: <AWSPreparedRequest stream_output=False, method=GET, url=https://dandiarchive.s3.amazonaws.com/?list-type=2&prefix=zarr%2Ff4fa5830-f449-4cc8-8f83-30944b36b20b%2F&continuation-token=SENSORED&encoding-type=url, headers={'User-Agent': b'Botocore/1.24.21 Python/3.8.13 Linux/5.10.0-13-amd64', 'amz-sdk-invocation-id': b'd7e380c6-318e-4dc8-be08-a304ff2591cb', 'amz-sdk-request': b'attempt=1'}>
2022-09-12T10:16:40-0400 [DEBUG   ] botocore.retryhandler: retry needed, retryable exception caught: Connection was closed before we received a valid response from endpoint URL: "https://dandiarchive.s3.amazonaws.com/?list-type=2&prefix=zarr%2Ff4fa5830-f449-4cc8-8f83-30944b36b20b%2F&continuation-token=SENSORED&encoding-type=url".
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://dandiarchive.s3.amazonaws.com/?list-type=2&prefix=zarr%2Ff4fa5830-f449-4cc8-8f83-30944b36b20b%2F&continuation-token=SENSORED&encoding-type=url".
2022-09-12T10:16:42-0400 [DEBUG   ] botocore.utils: URI updated to: https://dandiarchive.s3.amazonaws.com/?list-type=2&prefix=zarr%2Ff4fa5830-f449-4cc8-8f83-30944b36b20b%2F&continuation-token=SENSORED&encoding-type=url
2022-09-12T10:16:42-0400 [DEBUG   ] botocore.endpoint: Sending http request: <AWSPreparedRequest stream_output=False, method=GET, url=https://dandiarchive.s3.amazonaws.com/?list-type=2&prefix=zarr%2Ff4fa5830-f449-4cc8-8f83-30944b36b20b%2F&continuation-token=SENSORED&encoding-type=url, headers={'User-Agent': b'Botocore/1.24.21 Python/3.8.13 Linux/5.10.0-13-amd64', 'amz-sdk-invocation-id': b'd7e380c6-318e-4dc8-be08-a304ff2591cb', 'amz-sdk-request': b'attempt=2; max=5'}>
```
so would need to look at other errors... and indeed the first one comes the PATCHing of descriptions which exceeds maximal retrying time.
```
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets/.git/dandi/backups2datalad$ grep Error: $PWD/2022.09.12.13.46.43Z.log | grep -v -e '^aiohttp.client_exceptions.ServerDisconnectedError' -e '^botocore.exceptions.ConnectionClosedError'  | head
2022-09-12T10:21:07-0400 [WARNING ] backups2datalad: Retrying PATCH request to https://api.github.com/repos/dandizarrs/1284a14f-fe4f-4dc3-b10d-48e5db8bf18d in 10.497600 seconds as it raised ReadError: 
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host dandiarchive.s3.amazonaws.com:443 ssl:default [None]
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://dandiarchive.s3.amazonaws.com/?list-type=2&prefix=zarr%2Ffb035cb4-6bf2-4072-8241-f9d8dbe92d72%2F&encoding-type=url"
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host dandiarchive.s3.amazonaws.com:443 ssl:default [None]
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://dandiarchive.s3.amazonaws.com/?list-type=2&prefix=zarr%2Ffb035cb4-6bf2-4072-8241-f9d8dbe92d72%2F&encoding-type=url"
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host dandiarchive.s3.amazonaws.com:443 ssl:default [None]
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://dandiarchive.s3.amazonaws.com/?versions&prefix=zarr%2Fa8bb4dc5-a4a2-4ec6-a666-8e432b281de2%2F&key-marker=zarr%2Fa8bb4dc5-a4a2-4ec6-a666-8e432b281de2%2F0%2F0%2F0%2F2%2F20%2F65&version-id-marker=oaX9k1iZJX21DPWFw1VNFb3NAOJZJmjl&encoding-type=url"
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host dandiarchive.s3.amazonaws.com:443 ssl:default [None]
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://dandiarchive.s3.amazonaws.com/?versions&prefix=zarr%2Fa8bb4dc5-a4a2-4ec6-a666-8e432b281de2%2F&key-marker=zarr%2Fa8bb4dc5-a4a2-4ec6-a666-8e432b281de2%2F0%2F0%2F0%2F2%2F20%2F65&version-id-marker=oaX9k1iZJX21DPWFw1VNFb3NAOJZJmjl&encoding-type=url"
AssertionError: feed_data after feed_eof
```

I will increase the number of retries, will add some jitter (so there is no identical retries time delays).

**Comment by yarikoptic** [comment]
happened again, see log 2022.09.21.17.03.13Z_filt.log . Those `feed_data` errors come very late in the file, about 99% in, and there is a number of those connection errors well ahead of it but they indeed probably were just retried, so we still don't know what is happening to lead to this. uff... wonders of debugging async code.  @jwodder -- any further ideas?  we still do not have any "Error parsing" logged, may be try/except should go wider -- e.g. around the `async` block?

**Comment by yarikoptic** [comment]
after all recent changes and using `--workers 2` -- haven't seen this for a while. let's assume that it is mitigated
