### ISSUE TITLE
asyncio.exceptions.CancelledError

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#261]
after filing 260, `git reset --hard` 000108 and rerunning reducing number of workers to 1 with hope to make logs etc easier to understand

```
python -m tools.backups2datalad -l INFO --backup-root /mnt/backup/dandi --config tools/backups2datalad.cfg.yaml update-from-backup --workers 1  000108
```

<details>
<summary>we got following crash logged in /mnt/backup/dandi/dandisets/.git/dandi/backups2datalad/2022.09.08.22.05.17Z.log</summary> 

```shell
2022-09-08T18:17:24-0400 [DEBUG   ] backups2datalad: Waiting for `git-annex find '--include=*' --json` [cwd=/mnt/backup/dandi/dandizarrs/66dbcc6f-0396-441d-aea6-0af8d5500562] to terminate
2022-09-08T18:17:24-0400 [DEBUG   ] backups2datalad: Waiting for `git-annex find '--include=*' --json` [cwd=/mnt/backup/dandi/dandizarrs/f7e3a560-c4a6-4652-b8c8-66afe580e4cb] to terminate
2022-09-08T18:17:25-0400 [DEBUG   ] backups2datalad: Waiting for `git-annex addurl -c annex.alwayscompact=false --batch --with-files --jobs 5 --json --json-error-messages --json-progress --raw` [cwd=/mnt/backup/dandi/dandisets/000108] to terminate
2022-09-08T18:17:25-0400 [DEBUG   ] backups2datalad: Waiting for `git-annex addurl -c annex.alwayscompact=false --batch --with-files --jobs 5 --json --json-error-messages --json-progress --raw` [cwd=/mnt/backup/dandi/dandisets/000108] to terminate
2022-09-08T18:17:25-0400 [DEBUG   ] backups2datalad: Command `git-annex addurl -c annex.alwayscompact=false --batch --with-files --jobs 5 --json --json-error-messages --json-progress --raw` [cwd=/mnt/backup/dandi/dandisets/000108] exited with return code 0
2022-09-08T18:17:27-0400 [ERROR   ] backups2datalad: Job failed on input <Dandiset 000108/draft>:
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpcore/backends/asyncio.py", line 101, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_core/_sockets.py", line 218, in connect_tcp
    await event.wait()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 658, in __aexit__
    raise CancelledError
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpcore/backends/asyncio.py", line 101, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpcore/_async/connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpcore/backends/auto.py", line 23, in connect_tcp
    return await self._backend.connect_tcp(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpcore/backends/asyncio.py", line 101, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/asyncer.py", line 483, in async_assets
    nursery.start_soon(dm.read_addurl)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/asyncer.py", line 148, in asset_loop
    async for asset in aia:
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/asyncer.py", line 596, in aiterassets
    async for asset in dandiset.aget_assets():
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/adandi.py", line 174, in aget_assets
    async for item in ait:
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/adandi.py", line 79, in paginate
    r = await self.get(r["next"])
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/adandi.py", line 50, in get
    return (await arequest(self.session, "GET", path, **kwargs)).json()
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/aioutil.py", line 156, in arequest
    raise e
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/aioutil.py", line 144, in arequest
    r = await client.request(method, url, follow_redirects=True, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_client.py", line 1506, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_client.py", line 1593, in send
    response = await self._send_handling_auth(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_client.py", line 1621, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_client.py", line 1658, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_client.py", line 1695, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/aioutil.py", line 189, in dowork
    outp = await func(inp)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 142, in update_dandiset
    changed, zarr_stats = await self.sync_dataset(dandiset, ds, dmanager)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 187, in sync_dataset
    await syncer.sync_assets(error_on_change)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/syncer.py", line 37, in sync_assets
    self.report = await async_assets(
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/asyncer.py", line 483, in async_assets
    nursery.start_soon(dm.read_addurl)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_client.py", line 1975, in __aexit__
    await self._transport.__aexit__(exc_type, exc_value, traceback)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpx/_transports/default.py", line 332, in __aexit__
    await self._pool.__aexit__(exc_type, exc_value, traceback)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 326, in __aexit__
    await self.aclose()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 312, in aclose
    raise RuntimeError(
RuntimeError: The connection pool was closed while 469 HTTP requests/responses were still in-flight.
```
</details>

and not clear what specific request timed out.  Could retried be added and logging improved @jwodder ?

**Comment by jwodder** [comment]
@yarikoptic Retrying is already implemented, and based on the traceback, it was in effect.  Grepping the logfile for "Retrying" shows numerous PATCH requests to GitHub (specifically, editing descriptions of dandizarrs repos) being retried due to ConnectTimeout errors.

**Comment by yarikoptic** [comment]
yes, some are indeed retried, but are all?  But what about all those `httpcore.ConnectTimeout` -- can figure out what those are about?

**Comment by jwodder** [comment]
@yarikoptic 

> yes, some are indeed retried, but are all?

I'm not clear on what you're asking.  What makes you think that some may not be retried?

> But what about all those `httpcore.ConnectTimeout` -- can figure out what those are about?

[The httpx documentation](https://www.python-httpx.org/exceptions/) describes `ConnectTimeout` as "Timed out while connecting to the host."

**Comment by yarikoptic** [comment]
> > But what about all those `httpcore.ConnectTimeout` -- can figure out what those are about?
> 
> [The httpx documentation](https://www.python-httpx.org/exceptions/) describes `ConnectTimeout` as "Timed out while connecting to the host."

can we discover which host/connection (url) that specific time out for?  I would expect there be no timeouts since we should be retrying for sufficient number of times/amount of time to mitigate any intermittent connectivity issues which might lead to such time outs.  But ATM such `ConnectTimetout` is too regular to be some intermittent issue.  But we need to figure out first what connection is timing out.

**Comment by jwodder** [comment]
@yarikoptic [As I said above](https://github.com/dandi/dandisets/issues/261#issuecomment-1242012023), the requests were all to GitHub repositories to edit their descriptions, though [GitHub's incident history](https://www.githubstatus.com/history) shows nothing relevant around that time.  Have the connection timeouts happened again since this issue was created?

**Comment by yarikoptic** [comment]
I believe it was reported at least on 1 subsequent run (and I have not done many more) too. Easy (although takes time due to humongous sizes) to check:

```shell
(base) dandi@drogon:/mnt/backup/dandi/dandisets/.git/dandi/backups2datalad$ grep -l httpcore.ConnectTimeout *Z.log
2022.09.08.18.27.28Z.log
2022.09.08.22.05.17Z.log
2022.09.09.13.53.32Z.log
```

In the most recent run still ongoing (2022.09.12.13.46.43Z.log) many are reported for retries to github:

```
2022-09-12T09:59:45-0400 [WARNING ] backups2datalad: Retrying PATCH request to https://api.github.com/repos/dandizarrs/a6d55ad8-a0a4-4c91-9750-b9ed924221f9 in 10.497600 seconds as it raised ConnectTimeout:
2022-09-12T09:59:51-0400 [WARNING ] backups2datalad: Retrying PATCH request to https://api.github.com/repos/dandizarrs/bb6777c8-a669-434f-84b2-99a3bae243b0 in 5.832000 seconds as it raised ConnectTimeout:
2022-09-12T09:59:55-0400 [WARNING ] backups2datalad: Retrying PATCH request to https://api.github.com/repos/dandizarrs/bf47be1a-4fed-4105-bcb4-c52534a45b82 in 1.800000 seconds as it raised ConnectTimeout:
2022-09-12T09:59:57-0400 [WARNING ] backups2datalad: Retrying PATCH request to https://api.github.com/repos/dandizarrs/efc53126-a540-4a71-b240-bd097bde6f6e in 5.832000 seconds as it raised ConnectTimeout:
2022-09-12T09:59:59-0400 [WARNING ] backups2datalad: Retrying PATCH request to https://api.github.com/repos/dandizarrs/f7e3a560-c4a6-4652-b8c8-66afe580e4cb in 1.800000 seconds as it raised ConnectTimeout:
2022-09-12T10:00:03-0400 [WARNING ] backups2datalad: Retrying PATCH request to https://api.github.com/repos/dandizarrs/b0b9b99f-145f-4a73-af16-de7642d1b35d in 10.497600 seconds as it raised ConnectTimeout:
2022-09-12T10:00:06-0400 [WARNING ] backups2datalad: Retrying PATCH request to https://api.github.com/repos/dandizarrs/93764879-c7b4-4f83-8edf-920ae3e1a8b6 in 1.000000 seconds as it raised ConnectTimeout:
2022-09-12T10:00:10-0400 [WARNING ] backups2datalad: Retrying PATCH request to https://api.github.com/repos/dandizarrs/66dbcc6f-0396-441d-aea6-0af8d5500562 in 5.832000 seconds as it raised ConnectTimeout:
2022-09-12T10:00:16-0400 [WARNING ] backups2datalad: Retrying PATCH request to https://api.github.com/repos/dandizarrs/a6d55ad8-a0a4-4c91-9750-b9ed924221f9 in 18.895680 seconds as it raised ConnectTimeout:
```
and it seems they come really tightly in time for different zarrs.  I wonder also why we are sending so many updates at the same time (we should not send any PATCH if nothing changed), but may be that is indeed the main underlying issue -- flooding github interface with those update.  I looked on how many those reported/retried:

```
(base) dandi@drogon:/mnt/backup/dandi/dandisets/.git/dandi/backups2datalad$ grep -c ConnectTimeout *Z.log | grep -v ':0$'
2022.09.01.17.02.07Z.log:1
2022.09.02.05.50.06Z.log:1
2022.09.04.05.50.10Z.log:1
2022.09.05.05.50.07Z.log:2
2022.09.08.18.27.28Z.log:169
2022.09.08.22.05.17Z.log:68
2022.09.09.13.53.32Z.log:64
2022.09.12.13.46.43Z.log:950
```

and finally this ongoing run failed - can look for details in 2022.09.12.13.46.43Z.log .

May be "stretching" retries for those PATCH (longer waits between etc) could provide some remedy? but more likely -- we should not try to PATCH if not needed if that is what is happening now.

**Comment by jwodder** [comment]
@yarikoptic In order to know whether PATCHing is needed, we'd need to retrieve the current repository descriptions, so we'd still be sending requests to GitHub.

**Comment by yarikoptic** [comment]
> @yarikoptic In order to know whether PATCHing is needed, we'd need to retrieve the current repository descriptions, so we'd still be sending requests to GitHub.

I get that, but I would assume that 
- `GET` is "cheaper" for github so timeouts are less likely
- may be those descriptions could be obtained in batch listing entire `dandizarrs/` organization on github?
- relates to https://github.com/dandi/dandisets/issues/255 in that we might want to make permanent record so we do not even consider GET/PATCH if already done for that state. E.g. upon successfull PATCH (or GET confirming that no change needed), in that dandizarr set e.g. `remotes.github.description-hexsha` to the hexsha of HEAD for which update has been done already.  Then while looping through dandizarrs - do not bother GET/PATCHing if HEAD hexsha remains the same as the one we stored.

**Comment by yarikoptic** [comment]
an update: with increased timeouts in recent commits (925bc36f4099ab2ac4572373ac196be13cfc7472) and adding jitter to the timeout intervals (so we do not timeout in batches, in 259ee84baecb25255245c2c78ae8be36341789a8), the script had been running for over a day. Due to I guess the low `--workers 1`  it is still running and seems to proceed quite slowly.  https://github.com/orgs/dandizarrs/repositories seems to have good (non-default) descriptions with sizes etc.

edit: according to https://github.com/orgs/dandizarrs/repositories?q=some+default&type=all&sort= we still have over 600 of repos with "some default" for the description. In the logs I currently see the script updating/populating fb8de3ae-0034-48c2-bef7-4516c283f1e7 zarr which was last updated in June on https://github.com/dandizarrs/fb8de3ae-0034-48c2-bef7-4516c283f1e7 and has "some default". Let's see if/when it would be done.

**Comment by yarikoptic** [comment]
I think we haven't observed it recently
