### ISSUE TITLE
save failed since 4 .zarr/ folders are just empty and not known to git

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#262]
Run of `python -m tools.backups2datalad -l INFO --backup-root /mnt/backup/dandi --config tools/backups2datalad.cfg.yaml update-from-backup --workers 1  000108 ` finished erroring out with

```
 'sub-MITU01/ses-20220309h18m20s33/micr/sub-MITU01_ses-20220309h18m20s33_sample-17_stain-YO_run-1_chunk-7_SPIM.ome.zarr', 'sub-MITU01/ses-20220309h18m20s33/micr/sub-MITU01_ses-20220309h18m20s33_sample-17_stain-YO_run-1_chunk-8_SPIM.ome.zarr']: File(s) unknown to git: "error: pathspec 'sub-MITU01/ses-20210718h00m37s58/micr/sub-MITU01_ses-20210718h00m37s58_sample-153_stain-NN_run-1_chunk-1_SPIM.ome.zarr' did not match any file(s) known to git\nerror: pathspec 'sub-MITU01/ses-20210718h00m37s58/micr/sub-MITU01_ses-20210718h00m37s58_sample-153_stain-NN_run-1_chunk-6_SPIM.ome.zarr' did not match any file(s) known to git\nerror: pathspec 'sub-MITU01/ses-20210719h09m41s20/micr/sub-MITU01_ses-20210719h09m41s20_sample-147_stain-LEC_run-1_chunk-6_SPIM.ome.zarr' did not match any file(s) known to git\nerror: pathspec 'sub-MITU01/ses-20210719h09m41s20/micr/sub-MITU01_ses-20210719h09m41s20_sample-147_stain-LEC_run-1_chunk-7_SPIM.ome.zarr' did not match any file(s) known to git"
2022-09-13T17:17:14-0400 [ERROR   ] backups2datalad: Job failed on input <Dandiset 000108/draft>:
Traceback (most recent call last):
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/aioutil.py", line 189, in dowork
    outp = await func(inp)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 142, in update_dandiset
    changed, zarr_stats = await self.sync_dataset(dandiset, ds, dmanager)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/datasetter.py", line 187, in sync_dataset
    await syncer.sync_assets(error_on_change)
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/syncer.py", line 37, in sync_assets
    self.report = await async_assets(
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/asyncer.py", line 564, in async_assets
    await ds.save(
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/adataset.py", line 126, in save
    await aruncmd(
  File "/mnt/backup/dandi/dandisets/tools/backups2datalad/aioutil.py", line 223, in aruncmd
    return await anyio.run_process(argstrs, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/anyio/_core/_subprocesses.py", line 90, in run_process
    raise CalledProcessError(cast(int, process.returncode), command, output, errors)
subprocess.CalledProcessError: Command '['datalad', 'save', '-d', '.', '-m', '[backups2datalad] 3281 files added, 19 files updated']' returned non-zero exit status 1.
...
```

so it seems ( but didn't double check yet) that may be prior #261 and #260 are "addressed". But for some reason we ended up with some .zarr which seems to be known assets but seems to be empty in that no actual data was downloaded

```
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets/000108$ git status | tail -n 6 | grep 'zarr' | while read zarr; do echo "==== $zarr"; ls -l $zarr; zid=$(jq < .dandi/assets.json | grep -A2  ${zarr%/} | awk '/zarr":/{print $2;}' | sed -e 's,",,g'); echo $zid ; git -C ../../dandizarrs/$zid status; ls -l ../../dandizarrs/$zid -a; curl -X 'GET'  "https://api.dandiarchive.org/api/zarr/$zid/"  -H 'accept: application/json' ; echo; done
==== sub-MITU01/ses-20210718h00m37s58/micr/sub-MITU01_ses-20210718h00m37s58_sample-153_stain-NN_run-1_chunk-1_SPIM.ome.zarr/
total 0
a8bb4dc5-a4a2-4ec6-a666-8e432b281de2
On branch draft
Your branch is based on 'github/draft', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .dandi/s3sync.json
        .dandi/zarr-checksum

nothing added to commit but untracked files present (use "git add" to track)
total 4
drwxr-sr-x 1 dandi dandi     64 Aug 23 08:50 .
drwxr-sr-x 1 dandi dandi 262944 Aug 17 09:51 ..
drwxr-sr-x 1 dandi dandi     76 Jul  5 16:16 .dandi
drwxr-sr-x 1 dandi dandi     40 Jul  5 14:03 .datalad
drwxr-sr-x 1 dandi dandi    192 Sep 13 17:46 .git
-rw-r--r-- 1 dandi dandi     55 Jul  5 14:03 .gitattributes
{"name":"sub-MITU01/ses-20210718h00m37s58/micr/sub-MITU01_ses-20210718h00m37s58_sample-153_stain-NN_run-1_chunk-1_SPIM.ome.zarr","dandiset":"000108","zarr_id":"a8bb4dc5-a4a2-4ec6-a666-8e432b281de2","status":"Complete","checksum":"3b4e603d332a3b3f83edd1287281f077-48935--7108473017","upload_in_progress":false,"file_count":48935,"size":7108473017}
==== sub-MITU01/ses-20210718h00m37s58/micr/sub-MITU01_ses-20210718h00m37s58_sample-153_stain-NN_run-1_chunk-6_SPIM.ome.zarr/
total 0
173b2109-932c-40d8-b261-64edf8c0155e
On branch draft
Your branch is based on 'github/draft', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .dandi/s3sync.json
        .dandi/zarr-checksum

nothing added to commit but untracked files present (use "git add" to track)
total 4
drwxr-sr-x 1 dandi dandi     64 Aug 23 08:49 .
drwxr-sr-x 1 dandi dandi 262944 Aug 17 09:51 ..
drwxr-sr-x 1 dandi dandi     76 Jul  5 16:30 .dandi
drwxr-sr-x 1 dandi dandi     40 Jul  5 15:04 .datalad
drwxr-sr-x 1 dandi dandi    192 Sep 13 17:46 .git
-rw-r--r-- 1 dandi dandi     55 Jul  5 15:04 .gitattributes
{"name":"sub-MITU01/ses-20210718h00m37s58/micr/sub-MITU01_ses-20210718h00m37s58_sample-153_stain-NN_run-1_chunk-6_SPIM.ome.zarr","dandiset":"000108","zarr_id":"173b2109-932c-40d8-b261-64edf8c0155e","status":"Complete","checksum":"1f8b779889d9120526b9f5a59c385a1f-48935--33865077414","upload_in_progress":false,"file_count":48935,"size":33865077414}
==== sub-MITU01/ses-20210719h09m41s20/micr/sub-MITU01_ses-20210719h09m41s20_sample-147_stain-LEC_run-1_chunk-6_SPIM.ome.zarr/
total 0
b96f717d-0bcd-46ca-a7a0-6bed68573bb8
On branch draft
Your branch is based on 'github/draft', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .dandi/s3sync.json
        .dandi/zarr-checksum

nothing added to commit but untracked files present (use "git add" to track)
total 4
drwxr-sr-x 1 dandi dandi     64 Aug 23 08:53 .
drwxr-sr-x 1 dandi dandi 262944 Aug 17 09:51 ..
drwxr-sr-x 1 dandi dandi     76 Jul  5 16:58 .dandi
drwxr-sr-x 1 dandi dandi     40 Jul  5 15:23 .datalad
drwxr-sr-x 1 dandi dandi    192 Sep 13 17:46 .git
-rw-r--r-- 1 dandi dandi     55 Jul  5 15:23 .gitattributes
{"name":"sub-MITU01/ses-20210719h09m41s20/micr/sub-MITU01_ses-20210719h09m41s20_sample-147_stain-LEC_run-1_chunk-6_SPIM.ome.zarr","dandiset":"000108","zarr_id":"b96f717d-0bcd-46ca-a7a0-6bed68573bb8","status":"Complete","checksum":"862eab04259f4e30ce810bb95a991fb0-64155--75312070260","upload_in_progress":false,"file_count":64155,"size":75312070260}
==== sub-MITU01/ses-20210719h09m41s20/micr/sub-MITU01_ses-20210719h09m41s20_sample-147_stain-LEC_run-1_chunk-7_SPIM.ome.zarr/
total 0
de8893c9-0313-488d-b363-ebb980a5957e
On branch draft
Your branch is based on 'github/draft', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .dandi/s3sync.json
        .dandi/zarr-checksum

nothing added to commit but untracked files present (use "git add" to track)
total 4
drwxr-sr-x 1 dandi dandi     64 Aug 23 08:54 .
drwxr-sr-x 1 dandi dandi 262944 Aug 17 09:51 ..
drwxr-sr-x 1 dandi dandi     76 Jul  5 17:01 .dandi
drwxr-sr-x 1 dandi dandi     40 Jul  5 15:34 .datalad
drwxr-sr-x 1 dandi dandi    192 Sep 13 17:46 .git
-rw-r--r-- 1 dandi dandi     55 Jul  5 15:34 .gitattributes
{"name":"sub-MITU01/ses-20210719h09m41s20/micr/sub-MITU01_ses-20210719h09m41s20_sample-147_stain-LEC_run-1_chunk-7_SPIM.ome.zarr","dandiset":"000108","zarr_id":"de8893c9-0313-488d-b363-ebb980a5957e","status":"Complete","checksum":"12169fb8c41cdd1baf0b16bf4279d995-64155--76205748148","upload_in_progress":false,"file_count":64155,"size":76205748148}
```

so zarrs are populated in the archive but not fetched properly locally.

**Comment by yarikoptic** [comment]
I think this was mitigated
