### ISSUE TITLE
FTR: populating with new URLs crashed on 000020

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#44]
```
2021-05-03T14:06:34-0400 [WARNING] datalad.annex TODO: --batch mode for whereis.  Operating serially
2021-05-03T14:06:34-0400 [INFO    ] use-new-urls.py Adding URL https://dandiarchive.s3.amazonaws.com/blobs/18e/3f6/18e3f6db-5105-4757-9766-933de9f9c88d?versionId=LH4JHscyZw3Lo7jC1eff0wLmMQdOFImO to asset
2021-05-03T14:06:34-0400 [INFO    ] use-new-urls.py Adding URL https://api.dandiarchive.org/api/dandisets/000020/versions/draft/assets/d637235c-3e4b-469e-be56-1238052e8969/download/ to asset
2021-05-03T14:06:36-0400 [INFO    ] use-new-urls.py Removing URL https://dandiarchive.s3.amazonaws.com/girder-assetstore/43/d3/43d3377556cc4edf8bb48e33cf2bbe16?versionId=_WL_leBea4mxZbDNxcojb0JyMNSuWdfK from asset
2021-05-03T14:06:36-0400 [INFO    ] use-new-urls.py Processing asset sub-724625943/sub-724625943_ses-727204432_icephys.nwb
[WARNING] TODO: --batch mode for whereis.  Operating serially
2021-05-03T14:06:36-0400 [WARNING] datalad.annex TODO: --batch mode for whereis.  Operating serially
2021-05-03T14:06:36-0400 [INFO    ] use-new-urls.py Adding URL https://dandiarchive.s3.amazonaws.com/blobs/a47/f91/a47f91d6-58a7-4b1e-9683-950704a46bae?versionId=dsqJnrhxw3EDPy1HAYZEvzQiCp7FArEk to asset
Traceback (most recent call last):
  File "tools/use-new-urls.py", line 122, in <module>
    main()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "tools/use-new-urls.py", line 45, in main
    URLUpdater(Path(datasets_path)).run(dandisets)
  File "tools/use-new-urls.py", line 60, in run
    self.update_dandiset_urls(did, ds)
  File "tools/use-new-urls.py", line 86, in update_dandiset_urls
    ds.repo.add_url_to_file(path, url, batch=True)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 239, in _wrap_normalize_path
    return func(self, file_new, *args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 2114, in add_url_to_file
    raise (AnnexBatchCommandError if batch else CommandError)(
datalad.support.exceptions.AnnexBatchCommandError: AnnexBatchCommandError: 'addurl' [Error, annex reported failure for addurl (url='https://dandiarchive.s3.amazonaws.com/blobs/a47/f91/a47f91d6-58a7-4b1e-9683-950704a46bae?versionId=dsqJnrhxw3EDPy1HAYZEvzQiCp7FArEk'): {'command': 'addurl', 'success': False, 'input': ['https://dandiarchive.s3.amazonaws.com/blobs/a47/f91/a47f91d6-58a7-4b1e-9683-950704a46bae?versionId=dsqJnrhxw3EDPy1HAYZEvzQiCp7FArEk sub-724625943/sub-724625943_ses-727204432_icephys.nwb'], 'error-messages': ['git-annex: HttpExceptionRequest Request {', '  host                 = "dandiarchive.s3.amazonaws.com"', '  port                 = 443', '  secure               = True', '  requestHeaders       = [("Accept-Encoding",""),("User-Agent","git-annex/8.20201007-g903b2f1")]', '  path                 = "/blobs/a47/f91/a47f91d6-58a7-4b1e-9683-950704a46bae"', '  queryString          = "?versionId=dsqJnrhxw3EDPy1HAYZEvzQiCp7FArEk"', '  method               = "HEAD"', '  proxy                = Nothing', '  rawBody              = False', '  redirectCount        = 10', '  responseTimeout      = ResponseTimeoutDefault', '  requestVersion       = HTTP/1.1', '}', ' (ConnectionFailure Network.Socket.connect: <socket: 18>: timeout (Connection timed out))'], 'file': 'sub-724625943/sub-724625943_ses-727204432_icephys.nwb'}]
```

```
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets$ ls -ld */sub-724625943/sub-724625943_ses-727204432_icephys.nwb
lrwxrwxrwx 1 dandi dandi 203 Oct 21  2020 000020/sub-724625943/sub-724625943_ses-727204432_icephys.nwb -> ../.git/annex/objects/Z1/Gq/SHA256E-s43547353--c9601ffb21267d9905792a3f0bd7d501693971fd8b39093b120c7ef0eec1aae4.nwb/SHA256E-s43547353--c9601ffb21267d9905792a3f0bd7d501693971fd8b39093b120c7ef0eec1aae4.nwb
```
I will retry on that one now

PS edit1: will need for cron job updating them will finish. I run while using `flock -E 0 -e -n /home/dandi/.run/backup2datalad-cron.lock ` to avoid possible multiple scripts trying to modify the same dandiset

**Comment by yarikoptic** [comment]
I think it went through ok on rerun, so must have been some connection issue, not worth "fixing" for one time script
