### ISSUE TITLE
robustify datalad's downloader?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandisets#91]
updating the substantially grown (without a copy in the "full S3 backup of the bucket") 000026 eventually errored out with
```
2021-10-01T12:26:59-0400 [ERROR   ] backups2datalad Operation failed with exception:
Traceback (most recent call last):
  File "tools/backups2datalad.py", line 782, in dandi_logging
    yield logfile
  File "tools/backups2datalad.py", line 338, in sync_dataset
    ds.download_url(urls=bucket_url, path=a.path)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 503, in apply_func
    return f(**kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 486, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 474, in return_func
    results = list(results)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 459, in generator_func
    raise IncompleteResultsError(
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'download_url',
  'exception_traceback': '[download_url.py:__call__:185,providers.py:download:482,base.py:download:521,base.py:access:169,base.py:_download:419,http.py:get_downloader_session:564]',
  'message': 'Failed to establish a new session 1 times. Last exception was: '
             "('Connection aborted.', RemoteDisconnected('Remote end closed "
             "connection without response')) [adapters.py:send:498] "
             '[http.py:get_downloader_session:564]',
  'path': '/mnt/backup/dandi/dandisets/000026/rawdata/sub-I48/ses-SPIM/microscopy/sub-I48_ses-SPIM_sample-BrocaAreaS02_stain-NeuN_chunk-09_SPIM.ome.tif',
  'status': 'error',
  'type': 'file'}]
Traceback (most recent call last):
  File "tools/backups2datalad.py", line 865, in <module>
    main()
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "tools/backups2datalad.py", line 696, in update_from_backup
    datasetter.update_from_backup(
  File "tools/backups2datalad.py", line 112, in update_from_backup
    changed = self.sync_dataset(d, ds)
  File "tools/backups2datalad.py", line 338, in sync_dataset
    ds.download_url(urls=bucket_url, path=a.path)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 503, in apply_func
    return f(**kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 486, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 474, in return_func
    results = list(results)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 459, in generator_func
    raise IncompleteResultsError(
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'download_url',
  'exception_traceback': '[download_url.py:__call__:185,providers.py:download:482,base.py:download:521,base.py:access:169,base.py:_download:419,http.py:get_downloader_session:564]',
  'message': 'Failed to establish a new session 1 times. Last exception was: '
             "('Connection aborted.', RemoteDisconnected('Remote end closed "
             "connection without response')) [adapters.py:send:498] "
             '[http.py:get_downloader_session:564]',
  'path': '/mnt/backup/dandi/dandisets/000026/rawdata/sub-I48/ses-SPIM/microscopy/sub-I48_ses-SPIM_sample-BrocaAreaS02_stain-NeuN_chunk-09_SPIM.ome.tif',
  'status': 'error',
  'type': 'file'}]
```
where the code says
```
        # TODO: our tests ATM aren't ready for retries, thus altogether disabled for now
        nretries = 1
        for retry in range(1, nretries+1):
```
so it seems should be just a matter of adding a config variable and mocking it away to 1 in the tests... 
positive side-effect of us committing each file (see #89 - might change) I think it should be safe to just restart and we might even do retries at our script level.

**Comment by yarikoptic** [comment]
notes: as it "stroke me" while talking about debouncing in https://github.com/dandi/dandisets/issues/89#issuecomment-932395440, by committing each downloaded file we ended up with an "inconsistent" state where .dandi/assets.jsonld are not actually reflecting what is present on the drive:
```
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets/000026$ grep rawdata/sub-I48/ses-SPIM/microscopy/sub-I48_ses-SPIM_sample-BrocaAreaS02_stain-NeuN_chunk-02_SPIM.ome.tif .dandi/assets.json 
(dandisets) dandi@drogon:/mnt/backup/dandi/dandisets/000026$ git log rawdata/sub-I48/ses-SPIM/microscopy/sub-I48_ses-SPIM_sample-BrocaAreaS02_stain-NeuN_chunk-02_SPIM.ome.tif
commit cc114a0a55a4b6212496801c5a3b682c1dc0eba4
Author: DANDI User <info@dandiarchive.org>
Date:   Thu Sep 30 18:11:40 2021 +0000

    [DATALAD] Download URLs
    
    URLs:
      https://dandiarchive.s3.amazonaws.com/blobs/e73/2af/e732afcc-4bfc-40c0-8964-03e22747fffa?versionId=GLqWFcCqA_GEJbn4G6q3cu3q7mNVlqou
```
and our logic is:
```
                        log.info(
                            "Asset not found in assetstore; downloading from %s",
                            bucket_url,
                        )   
                        try:
                            dest.unlink()
                        except FileNotFoundError:
                            pass
                        with custom_commit_date(dandiset.version.modified):
                            ds.download_url(urls=bucket_url, path=a.path)
```
but it is conditioned on `to_update` for which we rely on dandi_hash comparison... cool -- should be "safe" and efficient to restart. Let's try

**Comment by yarikoptic** [comment]
I do not think we use that one, or of we do - may be already retry since didn't see errors of this kind recently
